package spicevids

import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/Wasylq/FSS/internal/scrapers/ayloutil"
	"github.com/Wasylq/FSS/scraper"
)

type collectionConfig struct {
	CollectionID int
	SiteID       string
	StudioName   string
}

var collections = []collectionConfig{
	{CollectionID: 68631, SiteID: "sv-100pctblack", StudioName: "100pctBlack"},
	{CollectionID: 68621, SiteID: "sv-100pcteuro", StudioName: "100pctEuro"},
	{CollectionID: 73501, SiteID: "sv-1111customs", StudioName: "1111Customs"},
	{CollectionID: 61231, SiteID: "sv-18virginsex", StudioName: "18VirginSex"},
	{CollectionID: 66991, SiteID: "sv-18vr", StudioName: "18VR"},
	{CollectionID: 57031, SiteID: "sv-18yearsold", StudioName: "18YearsOld"},
	{CollectionID: 60161, SiteID: "sv-21naturals", StudioName: "21Naturals"},
	{CollectionID: 58131, SiteID: "sv-21sextreme", StudioName: "21Sextreme"},
	{CollectionID: 58121, SiteID: "sv-21sextury", StudioName: "21Sextury"},
	{CollectionID: 63641, SiteID: "sv-2girls1camera", StudioName: "2Girls1Camera"},
	{CollectionID: 68321, SiteID: "sv-2muchlove", StudioName: "2MuchLove"},
	{CollectionID: 67791, SiteID: "sv-3holegirls", StudioName: "3-HoleGirls"},
	{CollectionID: 63901, SiteID: "sv-3wayporn", StudioName: "3-WayPorn"},
	{CollectionID: 71201, SiteID: "sv-3dxpassion", StudioName: "3DXPassion"},
	{CollectionID: 71811, SiteID: "sv-4kcfnm", StudioName: "4KCFNM"},
	{CollectionID: 70951, SiteID: "sv-5kporn", StudioName: "5KPorn"},
	{CollectionID: 73171, SiteID: "sv-5kteens", StudioName: "5KTeens"},
	{CollectionID: 75531, SiteID: "sv-6bitches", StudioName: "6Bitches"},
	{CollectionID: 117601, SiteID: "sv-8teenhub", StudioName: "8TeenHub"},
	{CollectionID: 79271, SiteID: "sv-academypov", StudioName: "AcademyPOV"},
	{CollectionID: 77211, SiteID: "sv-academywrestling", StudioName: "AcademyWrestling"},
	{CollectionID: 64121, SiteID: "sv-ad4x", StudioName: "AD4X"},
	{CollectionID: 62061, SiteID: "sv-adamandevevod", StudioName: "AdamandEveVOD"},
	{CollectionID: 71471, SiteID: "sv-adptube", StudioName: "ADPTube"},
	{CollectionID: 60401, SiteID: "sv-adultmobile", StudioName: "AdultMobile"},
	{CollectionID: 71001, SiteID: "sv-adulttime", StudioName: "AdultTime"},
	{CollectionID: 68171, SiteID: "sv-africanorgasm", StudioName: "AfricanOrgasm"},
	{CollectionID: 70061, SiteID: "sv-agirlknows", StudioName: "AGirlKnows"},
	{CollectionID: 65311, SiteID: "sv-alexlegend", StudioName: "AlexLegend"},
	{CollectionID: 114411, SiteID: "sv-alexromero", StudioName: "AlexRomero"},
	{CollectionID: 71181, SiteID: "sv-alexromeroclassix", StudioName: "AlexRomeroClassix"},
	{CollectionID: 65921, SiteID: "sv-allanalallthetime", StudioName: "AllAnalAllTheTime"},
	{CollectionID: 57361, SiteID: "sv-allgirlmassage", StudioName: "AllGirlMassage"},
	{CollectionID: 73761, SiteID: "sv-allgroupsex", StudioName: "AllGroupSex"},
	{CollectionID: 64611, SiteID: "sv-allisonmoorexxx", StudioName: "AllisonMooreXXX"},
	{CollectionID: 78411, SiteID: "sv-allsexmovie", StudioName: "AllSexMovie"},
	{CollectionID: 65561, SiteID: "sv-allthoseboobs", StudioName: "AllThoseBoobs"},
	{CollectionID: 65571, SiteID: "sv-allthosegirls", StudioName: "AllThoseGirls"},
	{CollectionID: 65581, SiteID: "sv-allthosemoms", StudioName: "AllThoseMoms"},
	{CollectionID: 67451, SiteID: "sv-alterotic", StudioName: "ALTErotic"},
	{CollectionID: 68101, SiteID: "sv-amafrench", StudioName: "AMAFrench"},
	{CollectionID: 79051, SiteID: "sv-amaraw", StudioName: "Amaraw"},
	{CollectionID: 68111, SiteID: "sv-amaspain", StudioName: "AMASpain"},
	{CollectionID: 73231, SiteID: "sv-amateureuro", StudioName: "AmateurEuro"},
	{CollectionID: 65531, SiteID: "sv-americanpornstar", StudioName: "American-Pornstar"},
	{CollectionID: 68311, SiteID: "sv-americanidolx", StudioName: "AmericanIdolX"},
	{CollectionID: 68301, SiteID: "sv-americanxxx", StudioName: "AmericanXXX"},
	{CollectionID: 64031, SiteID: "sv-analbeauty", StudioName: "Anal-Beauty"},
	{CollectionID: 82241, SiteID: "sv-anal4k", StudioName: "Anal4K"},
	{CollectionID: 68011, SiteID: "sv-analinvasion", StudioName: "AnalInvasion"},
	{CollectionID: 64281, SiteID: "sv-analized", StudioName: "Analized"},
	{CollectionID: 117211, SiteID: "sv-andystar", StudioName: "AndyStar"},
	{CollectionID: 61581, SiteID: "sv-angelasommers", StudioName: "AngelaSommers"},
	{CollectionID: 61111, SiteID: "sv-angelinacastro", StudioName: "AngelinaCastro"},
	{CollectionID: 57911, SiteID: "sv-angelinavalentine", StudioName: "AngelinaValentine"},
	{CollectionID: 56951, SiteID: "sv-anilos", StudioName: "Anilos"},
	{CollectionID: 62491, SiteID: "sv-archangelvideo", StudioName: "ArchAngelVideo"},
	{CollectionID: 117371, SiteID: "sv-armyproductions", StudioName: "ArmyProductions"},
	{CollectionID: 77191, SiteID: "sv-asiam", StudioName: "AsiaM"},
	{CollectionID: 79331, SiteID: "sv-asianaddiction", StudioName: "AsianAddiction"},
	{CollectionID: 66451, SiteID: "sv-assparade", StudioName: "AssParade"},
	{CollectionID: 61161, SiteID: "sv-atkexotics", StudioName: "ATKExotics"},
	{CollectionID: 59281, SiteID: "sv-atkgalleria", StudioName: "ATKGalleria"},
	{CollectionID: 60021, SiteID: "sv-atkgirlfriends", StudioName: "ATKGirlfriends"},
	{CollectionID: 59271, SiteID: "sv-atkhairy", StudioName: "ATKHairy"},
	{CollectionID: 117741, SiteID: "sv-atventertainment", StudioName: "ATVEntertainment"},
	{CollectionID: 57901, SiteID: "sv-avadevine", StudioName: "AvaDevine"},
	{CollectionID: 114911, SiteID: "sv-azpornstar", StudioName: "AZPornstar"},
	{CollectionID: 72751, SiteID: "sv-azureskyfilms", StudioName: "AzureSkyFilms"},
	{CollectionID: 70501, SiteID: "sv-baberotica", StudioName: "Baberotica"},
	{CollectionID: 74591, SiteID: "sv-baberoticavr", StudioName: "BaberoticaVR"},
	{CollectionID: 68461, SiteID: "sv-babevr", StudioName: "BabeVR"},
	{CollectionID: 79261, SiteID: "sv-backdoorpov", StudioName: "BackdoorPOV"},
	{CollectionID: 66671, SiteID: "sv-backroomfacials", StudioName: "BackroomFacials"},
	{CollectionID: 113531, SiteID: "sv-badfamilypov", StudioName: "BadFamilyPOV"},
	{CollectionID: 63081, SiteID: "sv-badoinkvr", StudioName: "BaDoinkVR"},
	{CollectionID: 65251, SiteID: "sv-baeb", StudioName: "BAEB"},
	{CollectionID: 57541, SiteID: "sv-baitbus", StudioName: "BaitBus"},
	{CollectionID: 74211, SiteID: "sv-bambulax", StudioName: "Bambulax"},
	{CollectionID: 65331, SiteID: "sv-bamvisions", StudioName: "BamVisions"},
	{CollectionID: 69461, SiteID: "sv-bananafever", StudioName: "BananaFever"},
	{CollectionID: 65361, SiteID: "sv-bangbus", StudioName: "BangBus"},
	{CollectionID: 64821, SiteID: "sv-bangcasting", StudioName: "BangCasting"},
	{CollectionID: 66091, SiteID: "sv-bangconfessions", StudioName: "BangConfessions"},
	{CollectionID: 65231, SiteID: "sv-banggonzo", StudioName: "BangGonzo"},
	{CollectionID: 66721, SiteID: "sv-bangingbeauties", StudioName: "BangingBeauties"},
	{CollectionID: 71581, SiteID: "sv-bangingfamily", StudioName: "BangingFamily"},
	{CollectionID: 65591, SiteID: "sv-bangmyboobies", StudioName: "BangMyBoobies"},
	{CollectionID: 66491, SiteID: "sv-bangpov", StudioName: "BangPOV"},
	{CollectionID: 64811, SiteID: "sv-bangrealteens", StudioName: "BangRealTeens"},
	{CollectionID: 74201, SiteID: "sv-bbcpie", StudioName: "BBCPie"},
	{CollectionID: 114401, SiteID: "sv-bevr", StudioName: "BEVR"},
	{CollectionID: 67841, SiteID: "sv-bibuddies", StudioName: "BiBuddies"},
	{CollectionID: 65631, SiteID: "sv-biempire", StudioName: "BiEmpire"},
	{CollectionID: 78211, SiteID: "sv-bigboobsatplay", StudioName: "BigBoobsAtPlay"},
	{CollectionID: 78871, SiteID: "sv-bigboobsfanclub", StudioName: "BIGBOOBSFANCLUB"},
	{CollectionID: 78941, SiteID: "sv-bigcockco", StudioName: "BIGCOCKCO"},
	{CollectionID: 66151, SiteID: "sv-bigcocksworld", StudioName: "BigCocksWorld"},
	{CollectionID: 63611, SiteID: "sv-biggulpgirls", StudioName: "BigGulpGirls"},
	{CollectionID: 72501, SiteID: "sv-bigjohnnyxxx", StudioName: "BigJohnnyXXX"},
	{CollectionID: 66551, SiteID: "sv-bigmouthfuls", StudioName: "BigMouthFuls"},
	{CollectionID: 66531, SiteID: "sv-bigtitcreampie", StudioName: "BigTitCreamPie"},
	{CollectionID: 63471, SiteID: "sv-bigtitsboss", StudioName: "BigTitsBoss"},
	{CollectionID: 66431, SiteID: "sv-bigtitsroundasses", StudioName: "BigTitsRoundAsses"},
	{CollectionID: 68021, SiteID: "sv-bigtitsworld", StudioName: "BigTitsWorld"},
	{CollectionID: 72671, SiteID: "sv-biguysfuck", StudioName: "BiGuysFuck"},
	{CollectionID: 75311, SiteID: "sv-biphoria", StudioName: "BiPhoria"},
	{CollectionID: 68181, SiteID: "sv-bisexillusion", StudioName: "BisexIllusion"},
	{CollectionID: 70071, SiteID: "sv-bitchesabroad", StudioName: "BitchesAbroad"},
	{CollectionID: 78541, SiteID: "sv-bitchgirlvideo", StudioName: "BitchGirlVideo"},
	{CollectionID: 78101, SiteID: "sv-bjraw", StudioName: "BJRaw"},
	{CollectionID: 74911, SiteID: "sv-blackcatproduction", StudioName: "BlackCatProduction"},
	{CollectionID: 79031, SiteID: "sv-blackcockpassion", StudioName: "BlackCockPassion"},
	{CollectionID: 78881, SiteID: "sv-blackdesire", StudioName: "BLACKDESIRE"},
	{CollectionID: 60821, SiteID: "sv-blacked", StudioName: "Blacked"},
	{CollectionID: 67441, SiteID: "sv-blackedraw", StudioName: "BlackedRaw"},
	{CollectionID: 65431, SiteID: "sv-blackmarketxxx", StudioName: "BlackMarketXXX"},
	{CollectionID: 71511, SiteID: "sv-blackmassivecocks", StudioName: "BlackMassiveCocks"},
	{CollectionID: 68521, SiteID: "sv-blackmoneyerotica", StudioName: "BlackMoneyErotica"},
	{CollectionID: 75431, SiteID: "sv-blackneed", StudioName: "BlackNeed"},
	{CollectionID: 77131, SiteID: "sv-blackpassion", StudioName: "BlackPassion"},
	{CollectionID: 65651, SiteID: "sv-blackpynk", StudioName: "BlackPynk"},
	{CollectionID: 68031, SiteID: "sv-blacksinner", StudioName: "BlackSinner"},
	{CollectionID: 78901, SiteID: "sv-blowme", StudioName: "BLOW-ME"},
	{CollectionID: 66741, SiteID: "sv-blowjobfridays", StudioName: "BlowjobFridays"},
	{CollectionID: 64771, SiteID: "sv-blowmepov", StudioName: "BlowMePOV"},
	{CollectionID: 77451, SiteID: "sv-blusherotica", StudioName: "BlushErotica"},
	{CollectionID: 60601, SiteID: "sv-bollywoodnudeshd", StudioName: "BollywoodNudesHD"},
	{CollectionID: 92871, SiteID: "sv-bosslesson", StudioName: "BossLesson"},
	{CollectionID: 74881, SiteID: "sv-bossygirls", StudioName: "BossyGirls"},
	{CollectionID: 67601, SiteID: "sv-boxofporn", StudioName: "BoxOfPorn"},
	{CollectionID: 59551, SiteID: "sv-boysfirsttime", StudioName: "BoysFirstTime"},
	{CollectionID: 117201, SiteID: "sv-bradmontana", StudioName: "BradMontana"},
	{CollectionID: 66391, SiteID: "sv-brandibelle", StudioName: "BrandiBelle"},
	{CollectionID: 61411, SiteID: "sv-brandnewamateurs", StudioName: "BrandNewAmateurs"},
	{CollectionID: 62501, SiteID: "sv-bratperversions", StudioName: "BratPerversions"},
	{CollectionID: 111481, SiteID: "sv-brattymilf", StudioName: "BrattyMilf"},
	{CollectionID: 66841, SiteID: "sv-brattysis", StudioName: "BrattySis"},
	{CollectionID: 69571, SiteID: "sv-bravomodels", StudioName: "BravoModels"},
	{CollectionID: 73891, SiteID: "sv-britishteens", StudioName: "BritishTeens"},
	{CollectionID: 79721, SiteID: "sv-britstudio", StudioName: "BritStudio"},
	{CollectionID: 114161, SiteID: "sv-brokestraightboys", StudioName: "BrokeStraightBoys"},
	{CollectionID: 66481, SiteID: "sv-brownbunnies", StudioName: "BrownBunnies"},
	{CollectionID: 64411, SiteID: "sv-bubblebuttbonanza", StudioName: "BubbleButtBonanza"},
	{CollectionID: 92981, SiteID: "sv-bukkakeorgy", StudioName: "BukkakeOrgy"},
	{CollectionID: 70221, SiteID: "sv-bumsbesuch", StudioName: "BumsBesuch"},
	{CollectionID: 70231, SiteID: "sv-bumsbuero", StudioName: "BumsBuero"},
	{CollectionID: 70081, SiteID: "sv-bumsbus", StudioName: "BumsBus"},
	{CollectionID: 75921, SiteID: "sv-bustysis", StudioName: "BustySis"},
	{CollectionID: 71601, SiteID: "sv-cam4", StudioName: "CAM4"},
	{CollectionID: 62221, SiteID: "sv-camsoda", StudioName: "CamSoda"},
	{CollectionID: 75841, SiteID: "sv-camvivian", StudioName: "CamVivian"},
	{CollectionID: 113711, SiteID: "sv-canaldeanal", StudioName: "CanalDeAnal"},
	{CollectionID: 62711, SiteID: "sv-candygirlvideo", StudioName: "CandyGirlVideo"},
	{CollectionID: 117621, SiteID: "sv-cannonproductions", StudioName: "CannonProductions"},
	{CollectionID: 60931, SiteID: "sv-carmenvalentina", StudioName: "CarmenValentina"},
	{CollectionID: 70261, SiteID: "sv-castingallaitaliana", StudioName: "CastingAllaItaliana"},
	{CollectionID: 60881, SiteID: "sv-castingcouchhd", StudioName: "CastingCouch-HD"},
	{CollectionID: 59041, SiteID: "sv-castingcouchx", StudioName: "CastingCouch-X"},
	{CollectionID: 70271, SiteID: "sv-castingfrancais", StudioName: "CastingFrancais"},
	{CollectionID: 66561, SiteID: "sv-catalinacruz", StudioName: "CatalinaCruz"},
	{CollectionID: 62521, SiteID: "sv-cbtandballbusting", StudioName: "CBTAndBallbusting"},
	{CollectionID: 65761, SiteID: "sv-cfnmsecret", StudioName: "CFNMSecret"},
	{CollectionID: 74571, SiteID: "sv-chadalva", StudioName: "ChadAlva"},
	{CollectionID: 61101, SiteID: "sv-charleechase", StudioName: "CharleeChase"},
	{CollectionID: 118991, SiteID: "sv-charlieforde", StudioName: "CharlieForde"},
	{CollectionID: 70091, SiteID: "sv-chicasloca", StudioName: "ChicasLoca"},
	{CollectionID: 69451, SiteID: "sv-chickpassamateurs", StudioName: "ChickPassAmateurs"},
	{CollectionID: 66501, SiteID: "sv-chongas", StudioName: "Chongas"},
	{CollectionID: 68731, SiteID: "sv-clubkayden", StudioName: "ClubKayden"},
	{CollectionID: 63711, SiteID: "sv-clublisadaniels", StudioName: "ClubLisaDaniels"},
	{CollectionID: 57271, SiteID: "sv-clubsweethearts", StudioName: "ClubSweethearts"},
	{CollectionID: 58341, SiteID: "sv-clubtug", StudioName: "ClubTug"},
	{CollectionID: 57871, SiteID: "sv-collegeblackgirls", StudioName: "CollegeBlackGirls"},
	{CollectionID: 57471, SiteID: "sv-collegerules", StudioName: "CollegeRules"},
	{CollectionID: 114941, SiteID: "sv-collegeuniform", StudioName: "CollegeUniform"},
	{CollectionID: 59251, SiteID: "sv-combatzonexxx", StudioName: "CombatZoneXXX"},
	{CollectionID: 73451, SiteID: "sv-concoxxxion", StudioName: "Concoxxxion"},
	{CollectionID: 114281, SiteID: "sv-cosplayfancy", StudioName: "CosplayFancy"},
	{CollectionID: 69471, SiteID: "sv-cosplayfeet", StudioName: "CosplayFeet"},
	{CollectionID: 63621, SiteID: "sv-cougarseason", StudioName: "CougarSeason"},
	{CollectionID: 112731, SiteID: "sv-crazypregnant", StudioName: "CrazyPregnant"},
	{CollectionID: 74541, SiteID: "sv-creepypa", StudioName: "CreepyPA"},
	{CollectionID: 67291, SiteID: "sv-cristiannlive", StudioName: "CristiAnnLive"},
	{CollectionID: 57051, SiteID: "sv-crueltyparty", StudioName: "CrueltyParty"},
	{CollectionID: 70201, SiteID: "sv-crunchboy", StudioName: "Crunchboy"},
	{CollectionID: 70831, SiteID: "sv-crushgirls", StudioName: "CrushGirls"},
	{CollectionID: 75551, SiteID: "sv-crushingaustria", StudioName: "CrushingAustria"},
	{CollectionID: 77201, SiteID: "sv-cuckhunter", StudioName: "CuckHunter"},
	{CollectionID: 68991, SiteID: "sv-cum4k", StudioName: "Cum4K"},
	{CollectionID: 103651, SiteID: "sv-cumbizz", StudioName: "CumBizz"},
	{CollectionID: 58351, SiteID: "sv-cumblastcity", StudioName: "CumBlastCity"},
	{CollectionID: 65741, SiteID: "sv-cumfiesta", StudioName: "CumFiesta"},
	{CollectionID: 93191, SiteID: "sv-cumrotic", StudioName: "Cumrotic"},
	{CollectionID: 80681, SiteID: "sv-cumswappingsis", StudioName: "CumSwappingSis"},
	{CollectionID: 67631, SiteID: "sv-cumtrainer", StudioName: "CumTrainer"},
	{CollectionID: 58751, SiteID: "sv-cutesunny", StudioName: "CuteSunny"},
	{CollectionID: 76501, SiteID: "sv-cutexteen", StudioName: "CuteXTeen"},
	{CollectionID: 59341, SiteID: "sv-czechhunter", StudioName: "CzechHunter"},
	{CollectionID: 73251, SiteID: "sv-czechsoles", StudioName: "CzechSoles"},
	{CollectionID: 64431, SiteID: "sv-dadcrush", StudioName: "DadCrush"},
	{CollectionID: 68071, SiteID: "sv-daddy4k", StudioName: "Daddy4K"},
	{CollectionID: 64391, SiteID: "sv-daddysworstnightmare", StudioName: "DaddysWorstNightmare"},
	{CollectionID: 58421, SiteID: "sv-danejones", StudioName: "DaneJones"},
	{CollectionID: 57691, SiteID: "sv-daringsex", StudioName: "DaringSex"},
	{CollectionID: 67701, SiteID: "sv-dateslam", StudioName: "DateSlam"},
	{CollectionID: 78751, SiteID: "sv-datezone", StudioName: "Datezone"},
	{CollectionID: 72161, SiteID: "sv-debt4k", StudioName: "Debt4K"},
	{CollectionID: 60951, SiteID: "sv-debtdandy", StudioName: "DebtDandy"},
	{CollectionID: 71701, SiteID: "sv-deeper", StudioName: "Deeper"},
	{CollectionID: 63601, SiteID: "sv-deepthroatsirens", StudioName: "DeepthroatSirens"},
	{CollectionID: 72281, SiteID: "sv-defeatedsexfight", StudioName: "DefeatedSexFight"},
	{CollectionID: 80041, SiteID: "sv-delphinefilms", StudioName: "DelphineFilms"},
	{CollectionID: 116791, SiteID: "sv-deluxedivas", StudioName: "DeluxeDivas"},
	{CollectionID: 82791, SiteID: "sv-desperateamateurs", StudioName: "DesperateAmateurs"},
	{CollectionID: 79901, SiteID: "sv-deutscheramateursex", StudioName: "DeutscherAmateurSex"},
	{CollectionID: 70281, SiteID: "sv-deutschlandreport", StudioName: "DeutschlandReport"},
	{CollectionID: 67891, SiteID: "sv-devianthardcore", StudioName: "DeviantHardcore"},
	{CollectionID: 57701, SiteID: "sv-devilsfilm", StudioName: "DevilsFilm"},
	{CollectionID: 63741, SiteID: "sv-dickdorm", StudioName: "DickDorm"},
	{CollectionID: 74011, SiteID: "sv-digitalclimaxxx", StudioName: "DigitalClimaxxx"},
	{CollectionID: 62141, SiteID: "sv-digitaldesire", StudioName: "DigitalDesire"},
	{CollectionID: 74431, SiteID: "sv-dirtycasting", StudioName: "DirtyCasting"},
	{CollectionID: 74441, SiteID: "sv-dirtychubby", StudioName: "DirtyChubby"},
	{CollectionID: 70631, SiteID: "sv-dirtydocsclub", StudioName: "DirtyDocsClub"},
	{CollectionID: 112771, SiteID: "sv-dirtyprivate", StudioName: "DirtyPrivate"},
	{CollectionID: 78231, SiteID: "sv-dirtyroleplays", StudioName: "DirtyRoleplays"},
	{CollectionID: 61981, SiteID: "sv-dirtystepdaughter", StudioName: "DirtyStepDaughter"},
	{CollectionID: 61971, SiteID: "sv-dirtystepsister", StudioName: "DirtyStepSister"},
	{CollectionID: 67041, SiteID: "sv-dirtytalk", StudioName: "DirtyTalk"},
	{CollectionID: 78891, SiteID: "sv-dirtyteentales", StudioName: "DIRTYTEENTALES"},
	{CollectionID: 76001, SiteID: "sv-docsquirt", StudioName: "DocSquirt"},
	{CollectionID: 75451, SiteID: "sv-doegirls", StudioName: "DOEGIRLS"},
	{CollectionID: 70291, SiteID: "sv-doeprojects", StudioName: "DoeProjects"},
	{CollectionID: 72531, SiteID: "sv-doggvision", StudioName: "DoggVision"},
	{CollectionID: 58811, SiteID: "sv-doghousedigital", StudioName: "DoghouseDigital"},
	{CollectionID: 64351, SiteID: "sv-domingoview", StudioName: "DomingoView"},
	{CollectionID: 68121, SiteID: "sv-dontsayaword", StudioName: "DontSayAWord"},
	{CollectionID: 66751, SiteID: "sv-dorminvasion", StudioName: "DormInvasion"},
	{CollectionID: 68191, SiteID: "sv-doublepenetrationparty", StudioName: "DoublePenetrationParty"},
	{CollectionID: 78911, SiteID: "sv-doublepleasure", StudioName: "DOUBLEPLEASURE"},
	{CollectionID: 58481, SiteID: "sv-doubleviewcasting", StudioName: "DoubleViewCasting"},
	{CollectionID: 72061, SiteID: "sv-downblousejerk", StudioName: "DownblouseJerk"},
	{CollectionID: 69871, SiteID: "sv-dreamgirlsmembers", StudioName: "DreamGirlsMembers"},
	{CollectionID: 62051, SiteID: "sv-dreamroom", StudioName: "Dreamroom"},
	{CollectionID: 116341, SiteID: "sv-dripdropprod", StudioName: "DripDropProd"},
	{CollectionID: 77261, SiteID: "sv-dudcast", StudioName: "DudCast"},
	{CollectionID: 64451, SiteID: "sv-dukeshardcorehoneys", StudioName: "DukesHardcoreHoneys"},
	{CollectionID: 69801, SiteID: "sv-earlmiller", StudioName: "EarlMiller"},
	{CollectionID: 68441, SiteID: "sv-elegantangel", StudioName: "ElegantAngel"},
	{CollectionID: 61141, SiteID: "sv-elegantraw", StudioName: "ElegantRaw"},
	{CollectionID: 60921, SiteID: "sv-eleganxia", StudioName: "Eleganxia"},
	{CollectionID: 118701, SiteID: "sv-enjoyx", StudioName: "EnjoyX"},
	{CollectionID: 76811, SiteID: "sv-epicafri", StudioName: "EpicAfri"},
	{CollectionID: 65841, SiteID: "sv-epicporn", StudioName: "EpicPorn"},
	{CollectionID: 67561, SiteID: "sv-ericjohnssexadventures", StudioName: "EricJohnsSexAdventures"},
	{CollectionID: 60361, SiteID: "sv-erito", StudioName: "Erito"},
	{CollectionID: 60611, SiteID: "sv-erosexoticahd", StudioName: "ErosExoticaHD"},
	{CollectionID: 62421, SiteID: "sv-eroticfemaledomination", StudioName: "EroticFemaleDomination"},
	{CollectionID: 72201, SiteID: "sv-erotichabit", StudioName: "EroticHabit"},
	{CollectionID: 66001, SiteID: "sv-eroticmixedwrestlingclub", StudioName: "EroticMixedWrestlingClub"},
	{CollectionID: 68711, SiteID: "sv-eroticnikki", StudioName: "EroticNikki"},
	{CollectionID: 70821, SiteID: "sv-erotikvonbenan", StudioName: "Erotikvonbenan"},
	{CollectionID: 67551, SiteID: "sv-erotiqueshoesex", StudioName: "ErotiqueShoeSex"},
	{CollectionID: 64231, SiteID: "sv-erotiquetvlive", StudioName: "ErotiqueTVLive"},
	{CollectionID: 63381, SiteID: "sv-eurocreme", StudioName: "Eurocreme"},
	{CollectionID: 65751, SiteID: "sv-eurosexparties", StudioName: "EuroSexParties"},
	{CollectionID: 69701, SiteID: "sv-evolvedfights", StudioName: "EvolvedFights"},
	{CollectionID: 72231, SiteID: "sv-evolvedfightslez", StudioName: "EvolvedFightsLez"},
	{CollectionID: 61091, SiteID: "sv-exotic4k", StudioName: "Exotic4K"},
	{CollectionID: 70991, SiteID: "sv-exposedbondage", StudioName: "ExposedBondage"},
	{CollectionID: 70301, SiteID: "sv-exposedcasting", StudioName: "ExposedCasting"},
	{CollectionID: 67731, SiteID: "sv-exposedfetish", StudioName: "ExposedFetish"},
	{CollectionID: 62351, SiteID: "sv-exposedwhores", StudioName: "ExposedWhores"},
	{CollectionID: 56941, SiteID: "sv-extrememoviepass", StudioName: "ExtremeMoviePass"},
	{CollectionID: 68431, SiteID: "sv-exxxteens", StudioName: "ExxxTeens"},
	{CollectionID: 74181, SiteID: "sv-eyeontheguy", StudioName: "EyeOnTheGuy"},
	{CollectionID: 62431, SiteID: "sv-facesittingbutts", StudioName: "FaceSittingButts"},
	{CollectionID: 66731, SiteID: "sv-facialfest", StudioName: "FacialFest"},
	{CollectionID: 80231, SiteID: "sv-facials4k", StudioName: "Facials4K"},
	{CollectionID: 63591, SiteID: "sv-facialsforever", StudioName: "FacialsForever"},
	{CollectionID: 75671, SiteID: "sv-faithanderson", StudioName: "FaithAnderson"},
	{CollectionID: 58441, SiteID: "sv-fakeagent", StudioName: "FakeAgent"},
	{CollectionID: 59941, SiteID: "sv-fakeagentuk", StudioName: "FakeAgentUK"},
	{CollectionID: 62241, SiteID: "sv-fakecop", StudioName: "FakeCop"},
	{CollectionID: 65931, SiteID: "sv-fakedrivingschool", StudioName: "FakeDrivingSchool"},
	{CollectionID: 60271, SiteID: "sv-fakehospital", StudioName: "FakeHospital"},
	{CollectionID: 67741, SiteID: "sv-fakehostel", StudioName: "FakeHostel"},
	{CollectionID: 70591, SiteID: "sv-fakehuboriginals", StudioName: "FakehubOriginals"},
	{CollectionID: 59411, SiteID: "sv-faketaxi", StudioName: "FakeTaxi"},
	{CollectionID: 67461, SiteID: "sv-familyhookups", StudioName: "FamilyHookups"},
	{CollectionID: 73531, SiteID: "sv-familyscrew", StudioName: "FamilyScrew"},
	{CollectionID: 72591, SiteID: "sv-familysinners", StudioName: "FamilySinners"},
	{CollectionID: 62201, SiteID: "sv-familystrokes", StudioName: "FamilyStrokes"},
	{CollectionID: 76961, SiteID: "sv-familyswapxxx", StudioName: "FamilySwapXXX"},
	{CollectionID: 74601, SiteID: "sv-familyxxx", StudioName: "FAMILYxxx"},
	{CollectionID: 59381, SiteID: "sv-fantasyhd", StudioName: "FantasyHD"},
	{CollectionID: 67241, SiteID: "sv-fapadoo", StudioName: "Fapadoo"},
	{CollectionID: 68641, SiteID: "sv-fapadooasian4k", StudioName: "FapadooAsian4K"},
	{CollectionID: 74921, SiteID: "sv-fapadoomassage4k", StudioName: "FapadooMassage4K"},
	{CollectionID: 74931, SiteID: "sv-fapadoothreesomes4k", StudioName: "FapadooThreesomes4K"},
	{CollectionID: 70051, SiteID: "sv-featurefilms", StudioName: "FeatureFilms"},
	{CollectionID: 78031, SiteID: "sv-feetishpov", StudioName: "FeetishPOV"},
	{CollectionID: 60591, SiteID: "sv-felluciablowhd", StudioName: "FelluciaBlowHD"},
	{CollectionID: 58871, SiteID: "sv-femaleagent", StudioName: "FemaleAgent"},
	{CollectionID: 62971, SiteID: "sv-femalefaketaxi", StudioName: "FemaleFakeTaxi"},
	{CollectionID: 61061, SiteID: "sv-femalemusclenetwork", StudioName: "FemaleMuscleNetwork"},
	{CollectionID: 62531, SiteID: "sv-femdomfootfetish", StudioName: "FemdomFootFetish"},
	{CollectionID: 74961, SiteID: "sv-femdomsex", StudioName: "FemdomSex"},
	{CollectionID: 58981, SiteID: "sv-femjoy", StudioName: "FemJoy"},
	{CollectionID: 103381, SiteID: "sv-ferrart", StudioName: "Ferr-Art"},
	{CollectionID: 117501, SiteID: "sv-fetishandbdsm", StudioName: "FetishAndBDSM"},
	{CollectionID: 75831, SiteID: "sv-fetishaustria", StudioName: "FetishAustria"},
	{CollectionID: 68041, SiteID: "sv-fetishdesire", StudioName: "FetishDesire"},
	{CollectionID: 71571, SiteID: "sv-fetishgoldxxx", StudioName: "FetishgoldXXX"},
	{CollectionID: 61221, SiteID: "sv-fetishnetwork", StudioName: "FetishNetwork"},
	{CollectionID: 76761, SiteID: "sv-fetishprime", StudioName: "FetishPrime"},
	{CollectionID: 61961, SiteID: "sv-fetishpros", StudioName: "FetishPros"},
	{CollectionID: 68501, SiteID: "sv-fillyfilms", StudioName: "FillyFilms"},
	{CollectionID: 63091, SiteID: "sv-filmyfantasy", StudioName: "FilmyFantasy"},
	{CollectionID: 68931, SiteID: "sv-filthflix", StudioName: "FilthFlix"},
	{CollectionID: 82951, SiteID: "sv-finishesthejob", StudioName: "FinishesTheJob"},
	{CollectionID: 67621, SiteID: "sv-finishhim", StudioName: "FinishHim"},
	{CollectionID: 58471, SiteID: "sv-firstanalquest", StudioName: "FirstAnalQuest"},
	{CollectionID: 61721, SiteID: "sv-firstclasspov", StudioName: "FirstClassPOV"},
	{CollectionID: 63481, SiteID: "sv-firsttimeauditions", StudioName: "FirstTimeAuditions"},
	{CollectionID: 70961, SiteID: "sv-firsttimers", StudioName: "FirstTimers"},
	{CollectionID: 65911, SiteID: "sv-fistertwister", StudioName: "FisterTwister"},
	{CollectionID: 69101, SiteID: "sv-fit18", StudioName: "Fit18"},
	{CollectionID: 64631, SiteID: "sv-fitnessrooms", StudioName: "FitnessRooms"},
	{CollectionID: 104771, SiteID: "sv-fittingroom", StudioName: "Fitting-Room"},
	{CollectionID: 62071, SiteID: "sv-footfetishbeauties", StudioName: "FootFetishBeauties"},
	{CollectionID: 107501, SiteID: "sv-footfetishcenter", StudioName: "FootFetishCenter"},
	{CollectionID: 74981, SiteID: "sv-footgirl", StudioName: "FootGirl"},
	{CollectionID: 64701, SiteID: "sv-footjobvirgin", StudioName: "FootJobVirgin"},
	{CollectionID: 63451, SiteID: "sv-forbiddenfruitsfilms", StudioName: "ForbiddenFruitsFilms"},
	{CollectionID: 68161, SiteID: "sv-foxxedup", StudioName: "FoxxedUp"},
	{CollectionID: 77541, SiteID: "sv-foxy4kme", StudioName: "Foxy4kme"},
	{CollectionID: 64911, SiteID: "sv-fragileslave", StudioName: "FragileSlave"},
	{CollectionID: 65141, SiteID: "sv-francescomozart", StudioName: "FrancescoMozart"},
	{CollectionID: 81981, SiteID: "sv-freeuse", StudioName: "FreeUse"},
	{CollectionID: 117151, SiteID: "sv-freeze", StudioName: "Freeze"},
	{CollectionID: 77101, SiteID: "sv-frenchpornamator", StudioName: "FrenchPornAmator"},
	{CollectionID: 79441, SiteID: "sv-freshandinnocent", StudioName: "FreshAndInnocent"},
	{CollectionID: 68201, SiteID: "sv-fuckandgo", StudioName: "FuckandGo"},
	{CollectionID: 66071, SiteID: "sv-fuckedfeet", StudioName: "FuckedFeet"},
	{CollectionID: 70311, SiteID: "sv-fuckedintraffic", StudioName: "FuckedInTraffic"},
	{CollectionID: 80021, SiteID: "sv-fuckersdudesfromfrance", StudioName: "FuckersDudesFromFrance"},
	{CollectionID: 59611, SiteID: "sv-fuckfatties", StudioName: "FuckFatties"},
	{CollectionID: 79231, SiteID: "sv-fuckfighters", StudioName: "FuckFighters"},
	{CollectionID: 66621, SiteID: "sv-fuckingawesome", StudioName: "FuckingAwesome"},
	{CollectionID: 66341, SiteID: "sv-fuckmedaddy", StudioName: "FuckMeDaddy"},
	{CollectionID: 58491, SiteID: "sv-fuckndrive", StudioName: "FucknDrive"},
	{CollectionID: 59431, SiteID: "sv-fuckonstreet", StudioName: "FuckOnStreet"},
	{CollectionID: 113691, SiteID: "sv-fuckpassvr", StudioName: "FuckPassVR"},
	{CollectionID: 66591, SiteID: "sv-fuckteam5", StudioName: "FuckTeam5"},
	{CollectionID: 65601, SiteID: "sv-fuckthosechicks", StudioName: "FuckThoseChicks"},
	{CollectionID: 65611, SiteID: "sv-fuckthosemoms", StudioName: "FuckThoseMoms"},
	{CollectionID: 78341, SiteID: "sv-fullpornnetwork", StudioName: "FullPornNetwork"},
	{CollectionID: 119953, SiteID: "sv-funsizedteens", StudioName: "FunSizedTeens"},
	{CollectionID: 61621, SiteID: "sv-gabbyquinteros", StudioName: "GabbyQuinteros"},
	{CollectionID: 78271, SiteID: "sv-gangbanggonewild", StudioName: "GangbangGoneWild"},
	{CollectionID: 75681, SiteID: "sv-gangjerks", StudioName: "GangJerks"},
	{CollectionID: 71461, SiteID: "sv-gaysight", StudioName: "GaySight"},
	{CollectionID: 63721, SiteID: "sv-getyourkneesdirty", StudioName: "GetYourKneesDirty"},
	{CollectionID: 62891, SiteID: "sv-gframpage", StudioName: "GFRampage"},
	{CollectionID: 79881, SiteID: "sv-gilfmilf", StudioName: "GilfMilf"},
	{CollectionID: 71671, SiteID: "sv-girlcum", StudioName: "GirlCum"},
	{CollectionID: 65981, SiteID: "sv-girlfriendsfeet", StudioName: "GirlFriendsFeet"},
	{CollectionID: 61931, SiteID: "sv-girlfriendsfilms", StudioName: "GirlfriendsFilms"},
	{CollectionID: 60811, SiteID: "sv-girlfriendsxxx", StudioName: "GirlfriendsXXX"},
	{CollectionID: 73191, SiteID: "sv-girlgirlmania", StudioName: "GirlGirlMania"},
	{CollectionID: 117221, SiteID: "sv-girlgirlxxx", StudioName: "GirlGirlXXX"},
	{CollectionID: 72251, SiteID: "sv-girlgrind", StudioName: "GirlGrind"},
	{CollectionID: 78991, SiteID: "sv-girlsdeep", StudioName: "GirlsDeep"},
	{CollectionID: 58411, SiteID: "sv-girlsgonewild", StudioName: "GirlsGoneWild"},
	{CollectionID: 71591, SiteID: "sv-girlshunter", StudioName: "GirlsHunter"},
	{CollectionID: 77031, SiteID: "sv-girlsonlyporn", StudioName: "GirlsOnlyPorn"},
	{CollectionID: 59301, SiteID: "sv-girlsoutwest", StudioName: "GirlsOutWest"},
	{CollectionID: 65291, SiteID: "sv-girlsrimming", StudioName: "GirlsRimming"},
	{CollectionID: 61081, SiteID: "sv-girlsway", StudioName: "Girlsway"},
	{CollectionID: 75951, SiteID: "sv-girlzlust", StudioName: "GirlzLust"},
	{CollectionID: 114391, SiteID: "sv-givingahandjob", StudioName: "GivingAHandjob"},
	{CollectionID: 66521, SiteID: "sv-gloryholeloads", StudioName: "GloryHoleLoads"},
	{CollectionID: 62731, SiteID: "sv-goldwinpass", StudioName: "GoldwinPass"},
	{CollectionID: 80781, SiteID: "sv-gotfilled", StudioName: "GotFilled"},
	{CollectionID: 75981, SiteID: "sv-gotmum", StudioName: "GotMum"},
	{CollectionID: 59541, SiteID: "sv-granddadz", StudioName: "GrandDadz"},
	{CollectionID: 67081, SiteID: "sv-grandmams", StudioName: "Grandmams"},
	{CollectionID: 114421, SiteID: "sv-grouphappiness", StudioName: "GroupHappiness"},
	{CollectionID: 72191, SiteID: "sv-groupsexgames", StudioName: "GroupSexGames"},
	{CollectionID: 73471, SiteID: "sv-gsporn", StudioName: "GSPorn"},
	{CollectionID: 74801, SiteID: "sv-handyman", StudioName: "HandyMan"},
	{CollectionID: 76841, SiteID: "sv-hardcoremassage", StudioName: "HardcoreMassage"},
	{CollectionID: 60411, SiteID: "sv-hardx", StudioName: "HardX"},
	{CollectionID: 70321, SiteID: "sv-hausfrauficken", StudioName: "HausfrauFicken"},
	{CollectionID: 69351, SiteID: "sv-heavyonhotties", StudioName: "HeavyOnHotties"},
	{CollectionID: 74381, SiteID: "sv-hentaied", StudioName: "Hentaied"},
	{CollectionID: 117881, SiteID: "sv-hentaimovie", StudioName: "HentaiMovie"},
	{CollectionID: 79951, SiteID: "sv-hentaipd", StudioName: "HentaiPD"},
	{CollectionID: 65221, SiteID: "sv-hentaipros", StudioName: "HentaiPros"},
	{CollectionID: 76161, SiteID: "sv-hentaiuniverse", StudioName: "HentaiUniverse"},
	{CollectionID: 70331, SiteID: "sv-herbigass", StudioName: "HerBigAss"},
	{CollectionID: 70101, SiteID: "sv-herlimit", StudioName: "HerLimit"},
	{CollectionID: 68651, SiteID: "sv-hitzefrei", StudioName: "Hitzefrei"},
	{CollectionID: 64241, SiteID: "sv-holed", StudioName: "Holed"},
	{CollectionID: 69271, SiteID: "sv-hollyrandall", StudioName: "HollyRandall"},
	{CollectionID: 58601, SiteID: "sv-homegrowngfs", StudioName: "HomegrownGFs"},
	{CollectionID: 56931, SiteID: "sv-homegrownvideo", StudioName: "HomegrownVideo"},
	{CollectionID: 62381, SiteID: "sv-hookuphotshot", StudioName: "HookupHotshot"},
	{CollectionID: 79291, SiteID: "sv-hormonetokyo", StudioName: "HormoneTokyo"},
	{CollectionID: 70031, SiteID: "sv-hornybirds", StudioName: "HornyBirds"},
	{CollectionID: 61171, SiteID: "sv-hornydreambabez", StudioName: "HornyDreamBabez"},
	{CollectionID: 70531, SiteID: "sv-hornyhostel", StudioName: "HornyHostel"},
	{CollectionID: 73241, SiteID: "sv-hornyhousehold", StudioName: "HornyHousehold"},
	{CollectionID: 65771, SiteID: "sv-hotbush", StudioName: "HotBush"},
	{CollectionID: 70551, SiteID: "sv-hotcrazymess", StudioName: "HotCrazyMess"},
	{CollectionID: 62781, SiteID: "sv-hotguysfuck", StudioName: "HotGuysFuck"},
	{CollectionID: 65171, SiteID: "sv-hothotfilms", StudioName: "HotHotFilms"},
	{CollectionID: 72351, SiteID: "sv-hotwifexxx", StudioName: "HotWifeXXX"},
	{CollectionID: 117471, SiteID: "sv-hugeboobsmilf", StudioName: "HugeBoobsMilf"},
	{CollectionID: 114431, SiteID: "sv-hugeinsertions", StudioName: "HugeInsertions"},
	{CollectionID: 79221, SiteID: "sv-hugepornselection", StudioName: "HugePornSelection"},
	{CollectionID: 75221, SiteID: "sv-humiliationaustria", StudioName: "HumiliationAustria"},
	{CollectionID: 79161, SiteID: "sv-hungpapi", StudioName: "HungPapi"},
	{CollectionID: 114441, SiteID: "sv-hungrybeauties", StudioName: "HungryBeauties"},
	{CollectionID: 68081, SiteID: "sv-hunt4k", StudioName: "Hunt4K"},
	{CollectionID: 56891, SiteID: "sv-hushpass", StudioName: "HushPass"},
	{CollectionID: 61241, SiteID: "sv-ifuckedherfinally", StudioName: "IFuckedHerFinally"},
	{CollectionID: 80161, SiteID: "sv-ignoringhandjobs", StudioName: "IgnoringHandjobs"},
	{CollectionID: 71831, SiteID: "sv-ihuntmycunt", StudioName: "IHuntMyCunt"},
	{CollectionID: 75771, SiteID: "sv-ikissgirls", StudioName: "IKissGirls"},
	{CollectionID: 114791, SiteID: "sv-ilovepov", StudioName: "ILovePOV"},
	{CollectionID: 79061, SiteID: "sv-iluvmilfs", StudioName: "ILuvMilfs"},
	{CollectionID: 79131, SiteID: "sv-iluvteens", StudioName: "ILuvTeens"},
	{CollectionID: 76081, SiteID: "sv-immoralfamily", StudioName: "ImmoralFamily"},
	{CollectionID: 59191, SiteID: "sv-immorallive", StudioName: "ImmoralLive"},
	{CollectionID: 76071, SiteID: "sv-immoralpov", StudioName: "ImmoralPOV"},
	{CollectionID: 63961, SiteID: "sv-immoralproductions", StudioName: "ImmoralProductions"},
	{CollectionID: 62541, SiteID: "sv-inescapablebondage", StudioName: "InescapableBondage"},
	{CollectionID: 77981, SiteID: "sv-inkasex", StudioName: "InkaSex"},
	{CollectionID: 73381, SiteID: "sv-inkedgurlz", StudioName: "InkedGurlz"},
	{CollectionID: 67271, SiteID: "sv-interraced", StudioName: "Interraced"},
	{CollectionID: 64371, SiteID: "sv-interracialpass", StudioName: "InterracialPass"},
	{CollectionID: 72831, SiteID: "sv-intimacyproductions", StudioName: "IntimacyProductions"},
	{CollectionID: 61731, SiteID: "sv-intimatelesbians", StudioName: "IntimateLesbians"},
	{CollectionID: 78051, SiteID: "sv-intimatepov", StudioName: "IntimatePOV"},
	{CollectionID: 70781, SiteID: "sv-italianfeet", StudioName: "ItalianFeet"},
	{CollectionID: 61601, SiteID: "sv-itscleolive", StudioName: "ItsCleoLive"},
	{CollectionID: 76141, SiteID: "sv-itspov", StudioName: "ItsPOV"},
	{CollectionID: 116561, SiteID: "sv-japanuncensored", StudioName: "Japan-Uncensored"},
	{CollectionID: 78241, SiteID: "sv-japanesehotties", StudioName: "JapaneseHotties"},
	{CollectionID: 60941, SiteID: "sv-japanhdv", StudioName: "JapanHDV"},
	{CollectionID: 67711, SiteID: "sv-japanlust", StudioName: "JapanLust"},
	{CollectionID: 74421, SiteID: "sv-japanpornjunky", StudioName: "JapanPornJunky"},
	{CollectionID: 74791, SiteID: "sv-japbliss", StudioName: "JapBliss"},
	{CollectionID: 77121, SiteID: "sv-japsluts", StudioName: "JAPSluts"},
	{CollectionID: 72311, SiteID: "sv-javhub", StudioName: "JAVHub"},
	{CollectionID: 66631, SiteID: "sv-jayspov", StudioName: "JaysPOV"},
	{CollectionID: 62741, SiteID: "sv-jelenajensen", StudioName: "JelenaJensen"},
	{CollectionID: 79431, SiteID: "sv-jerkaoke", StudioName: "Jerkaoke"},
	{CollectionID: 78131, SiteID: "sv-jerkingstuds", StudioName: "JerkingStuds"},
	{CollectionID: 73461, SiteID: "sv-jerkmate", StudioName: "Jerkmate"},
	{CollectionID: 58101, SiteID: "sv-jerkoffinstructions", StudioName: "JerkOffInstructions"},
	{CollectionID: 74871, SiteID: "sv-jerkygirls", StudioName: "JerkyGirls"},
	{CollectionID: 75641, SiteID: "sv-jerkygirlspresentsmilfcumsluts", StudioName: "JerkyGirlsPresents MILFCumSluts"},
	{CollectionID: 75661, SiteID: "sv-jerkygirlspresentsteenhandjobs", StudioName: "JerkyGirlsPresents TeenHandjobs"},
	{CollectionID: 61381, SiteID: "sv-jesseloads", StudioName: "JesseLoads"},
	{CollectionID: 61741, SiteID: "sv-jessicajaymes", StudioName: "JessicaJaymes"},
	{CollectionID: 62801, SiteID: "sv-jizstop", StudioName: "Jizstop"},
	{CollectionID: 58501, SiteID: "sv-jizzonteens", StudioName: "JizzOnTeens"},
	{CollectionID: 67471, SiteID: "sv-jizzorama", StudioName: "JizzOrama"},
	{CollectionID: 79541, SiteID: "sv-joannaangel", StudioName: "JoannaAngel"},
	{CollectionID: 63461, SiteID: "sv-jodiwest", StudioName: "JodiWest"},
	{CollectionID: 67071, SiteID: "sv-jonnidarkko", StudioName: "JonniDarkko"},
	{CollectionID: 60221, SiteID: "sv-joshstonexxx", StudioName: "JoshStoneXXX"},
	{CollectionID: 60281, SiteID: "sv-joybear", StudioName: "JoyBear"},
	{CollectionID: 58241, SiteID: "sv-joymii", StudioName: "Joymii"},
	{CollectionID: 60891, SiteID: "sv-juliaannlive", StudioName: "JuliaAnnLive"},
	{CollectionID: 78841, SiteID: "sv-just4men", StudioName: "JUST4MEN"},
	{CollectionID: 68221, SiteID: "sv-justgreatass", StudioName: "JustGreatAss"},
	{CollectionID: 72731, SiteID: "sv-justpov", StudioName: "JustPOV"},
	{CollectionID: 59751, SiteID: "sv-karupshometownamateurs", StudioName: "KarupsHometownAmateurs"},
	{CollectionID: 59771, SiteID: "sv-karupsolderwomen", StudioName: "KarupsOlderWomen"},
	{CollectionID: 75461, SiteID: "sv-karupspov", StudioName: "KarupsPOV"},
	{CollectionID: 59761, SiteID: "sv-karupsprivatecollection", StudioName: "KarupsPrivateCollection"},
	{CollectionID: 72331, SiteID: "sv-karupssolo", StudioName: "KarupsSolo"},
	{CollectionID: 58041, SiteID: "sv-killergram", StudioName: "Killergram"},
	{CollectionID: 66801, SiteID: "sv-kimberleeofficial", StudioName: "KimberLeeOfficial"},
	{CollectionID: 72541, SiteID: "sv-kingofmallorca", StudioName: "KingOfMallorca"},
	{CollectionID: 65201, SiteID: "sv-kingsoffetish", StudioName: "KingsOfFetish"},
	{CollectionID: 72761, SiteID: "sv-kingsoffetishasian", StudioName: "KingsOfFetishAsian"},
	{CollectionID: 72371, SiteID: "sv-kingsoffetishbbw", StudioName: "KingsOfFetishBBW"},
	{CollectionID: 72381, SiteID: "sv-kingsoffetishbigboobs", StudioName: "KingsOfFetishBigBoobs"},
	{CollectionID: 72391, SiteID: "sv-kingsoffetishfamilyroleplay", StudioName: "KingsOfFetishFamilyRoleplay"},
	{CollectionID: 72441, SiteID: "sv-kingsoffetishgay", StudioName: "KingsOfFetishGay"},
	{CollectionID: 72771, SiteID: "sv-kingsoffetishgranny", StudioName: "KingsOfFetishGranny"},
	{CollectionID: 76331, SiteID: "sv-kingsoffetishjav", StudioName: "KingsOfFetishJav"},
	{CollectionID: 72411, SiteID: "sv-kingsoffetishlesbian", StudioName: "KingsOfFetishLesbian"},
	{CollectionID: 72421, SiteID: "sv-kingsoffetishpregnant", StudioName: "KingsOfFetishPregnant"},
	{CollectionID: 72401, SiteID: "sv-kingsoffetishteen", StudioName: "KingsOfFetishTeen"},
	{CollectionID: 78161, SiteID: "sv-koentertainments", StudioName: "KOEntertainments"},
	{CollectionID: 66811, SiteID: "sv-kumalott", StudioName: "Kumalott"},
	{CollectionID: 74371, SiteID: "sv-ladieswithtalent", StudioName: "LadiesWithTalent"},
	{CollectionID: 64661, SiteID: "sv-lanewgirl", StudioName: "LANewGirl"},
	{CollectionID: 70351, SiteID: "sv-lasfolladoras", StudioName: "LasFolladoras"},
	{CollectionID: 64721, SiteID: "sv-lasublimexxx", StudioName: "LaSublimeXXX"},
	{CollectionID: 67141, SiteID: "sv-lasvegasamateurs", StudioName: "LasVegasAmateurs"},
	{CollectionID: 78821, SiteID: "sv-latinamateur", StudioName: "LATINAMATEUR"},
	{CollectionID: 114381, SiteID: "sv-latinamilf", StudioName: "LatinaMilf"},
	{CollectionID: 66601, SiteID: "sv-latinarampage", StudioName: "LatinaRampage"},
	{CollectionID: 65241, SiteID: "sv-latinaspice", StudioName: "LatinaSpice"},
	{CollectionID: 64051, SiteID: "sv-lederhosengangbang", StudioName: "LederhosenGangbang"},
	{CollectionID: 57861, SiteID: "sv-lelulove", StudioName: "LeluLove"},
	{CollectionID: 79301, SiteID: "sv-lemonjuice", StudioName: "LemonJuice"},
	{CollectionID: 70841, SiteID: "sv-leonstv", StudioName: "LeonsTV"},
	{CollectionID: 99331, SiteID: "sv-lesarchive", StudioName: "LesArchive"},
	{CollectionID: 58271, SiteID: "sv-lesbea", StudioName: "Lesbea"},
	{CollectionID: 76751, SiteID: "sv-lesbianfantasies", StudioName: "LesbianFantasies"},
	{CollectionID: 78851, SiteID: "sv-lesbiangirlfriends", StudioName: "LESBIANGIRLFRIENDS"},
	{CollectionID: 68231, SiteID: "sv-lesbianillusion", StudioName: "LesbianIllusion"},
	{CollectionID: 66141, SiteID: "sv-lesbianlust", StudioName: "LesbianLust"},
	{CollectionID: 79911, SiteID: "sv-lesbiansexuality", StudioName: "LesbianSexuality"},
	{CollectionID: 60641, SiteID: "sv-lesbiantribe", StudioName: "LesbianTribe"},
	{CollectionID: 68491, SiteID: "sv-lesworship", StudioName: "LesWorship"},
	{CollectionID: 70151, SiteID: "sv-letsdoeit", StudioName: "LetsDoeIt"},
	{CollectionID: 82501, SiteID: "sv-letsdoeitbonus", StudioName: "LetsDoeItBONUS"},
	{CollectionID: 62961, SiteID: "sv-letsfuckoutside", StudioName: "LetsFuckOutside"},
	{CollectionID: 73521, SiteID: "sv-letsgobi", StudioName: "LetsGoBi"},
	{CollectionID: 73881, SiteID: "sv-letthemwatch", StudioName: "LetThemWatch"},
	{CollectionID: 73831, SiteID: "sv-lexsteelexxx", StudioName: "LexSteeleXXX"},
	{CollectionID: 59291, SiteID: "sv-lezkiss", StudioName: "LezKiss"},
	{CollectionID: 69181, SiteID: "sv-lezmates", StudioName: "LezMates"},
	{CollectionID: 71081, SiteID: "sv-lezpov", StudioName: "LezPOV"},
	{CollectionID: 72601, SiteID: "sv-lezziebff", StudioName: "LezzieBFF"},
	{CollectionID: 59141, SiteID: "sv-lifeselector", StudioName: "LifeSelector"},
	{CollectionID: 66271, SiteID: "sv-liftandcarryclub", StudioName: "LiftAndCarryClub"},
	{CollectionID: 58521, SiteID: "sv-lisariveraxo", StudioName: "LisaRiveraXO"},
	{CollectionID: 68091, SiteID: "sv-loan4k", StudioName: "Loan4K"},
	{CollectionID: 70361, SiteID: "sv-losconsoladores", StudioName: "LosConsoladores"},
	{CollectionID: 59691, SiteID: "sv-lovehomeporn", StudioName: "LoveHomePorn"},
	{CollectionID: 68611, SiteID: "sv-lovelexilore", StudioName: "LoveLexiLore"},
	{CollectionID: 79991, SiteID: "sv-ltgsexmovies", StudioName: "LTGSexMovies"},
	{CollectionID: 63111, SiteID: "sv-lubed", StudioName: "Lubed"},
	{CollectionID: 72661, SiteID: "sv-lustfeed", StudioName: "LustFeed"},
	{CollectionID: 74451, SiteID: "sv-lustyxxxfamily", StudioName: "LustyXXXFamily"},
	{CollectionID: 61841, SiteID: "sv-maggiegreen", StudioName: "MaggieGreen"},
	{CollectionID: 66681, SiteID: "sv-magicalfeet", StudioName: "MagicalFeet"},
	{CollectionID: 113681, SiteID: "sv-magicasianpussy", StudioName: "MagicAsianPussy"},
	{CollectionID: 117421, SiteID: "sv-magnusfilmes", StudioName: "MagnusFilmes"},
	{CollectionID: 58901, SiteID: "sv-magnusmuscle", StudioName: "MagnusMuscle"},
	{CollectionID: 73221, SiteID: "sv-mamacitaz", StudioName: "MamacitaZ"},
	{CollectionID: 79511, SiteID: "sv-mandymarx", StudioName: "MandyMarx"},
	{CollectionID: 64001, SiteID: "sv-manojob", StudioName: "ManoJob"},
	{CollectionID: 73541, SiteID: "sv-mariskax", StudioName: "MariskaX"},
	{CollectionID: 76861, SiteID: "sv-maskjoker", StudioName: "MaskJoker"},
	{CollectionID: 76521, SiteID: "sv-maskpark", StudioName: "MaskPark"},
	{CollectionID: 56971, SiteID: "sv-massagecreep", StudioName: "MassageCreep"},
	{CollectionID: 59311, SiteID: "sv-massagerooms", StudioName: "MassageRooms"},
	{CollectionID: 78331, SiteID: "sv-mature4k", StudioName: "Mature4K"},
	{CollectionID: 71871, SiteID: "sv-maturegapers", StudioName: "MatureGapers"},
	{CollectionID: 71991, SiteID: "sv-maturegynospy", StudioName: "MatureGynoSpy"},
	{CollectionID: 78781, SiteID: "sv-maturesvr", StudioName: "MaturesVR"},
	{CollectionID: 69831, SiteID: "sv-maxinex", StudioName: "MaxineX"},
	{CollectionID: 61641, SiteID: "sv-meanmassages", StudioName: "MeanMassages"},
	{CollectionID: 60211, SiteID: "sv-men", StudioName: "Men"},
	{CollectionID: 78591, SiteID: "sv-metrofetishmodels", StudioName: "MetroFetishModels"},
	{CollectionID: 61511, SiteID: "sv-miakhalifa", StudioName: "MiaKhalifa"},
	{CollectionID: 65781, SiteID: "sv-mikeinbrazil", StudioName: "MikeInBrazil"},
	{CollectionID: 81381, SiteID: "sv-milfed", StudioName: "MILFED"},
	{CollectionID: 78861, SiteID: "sv-milfgrannystore", StudioName: "MILFGRANNYSTORE"},
	{CollectionID: 68131, SiteID: "sv-milfinlove", StudioName: "MilfInLove"},
	{CollectionID: 113721, SiteID: "sv-milfknowhow", StudioName: "MilfKnowHow"},
	{CollectionID: 63501, SiteID: "sv-milfnextdoor", StudioName: "MILFNextDoor"},
	{CollectionID: 67281, SiteID: "sv-milfpower", StudioName: "MilfPower"},
	{CollectionID: 66541, SiteID: "sv-milfsoup", StudioName: "MilfSoup"},
	{CollectionID: 119321, SiteID: "sv-milfucked", StudioName: "MiLFUCKED"},
	{CollectionID: 116461, SiteID: "sv-milfy", StudioName: "Milfy"},
	{CollectionID: 80031, SiteID: "sv-milkyperu", StudioName: "MilkyPeru"},
	{CollectionID: 65491, SiteID: "sv-mmm100", StudioName: "MMM100"},
	{CollectionID: 76801, SiteID: "sv-modelcompilations", StudioName: "ModelCompilations"},
	{CollectionID: 66371, SiteID: "sv-moethemonster", StudioName: "MoeTheMonster"},
	{CollectionID: 117021, SiteID: "sv-mofozo", StudioName: "Mofozo"},
	{CollectionID: 72511, SiteID: "sv-momdrips", StudioName: "MomDrips"},
	{CollectionID: 70041, SiteID: "sv-momknowsbest", StudioName: "MomKnowsBest"},
	{CollectionID: 79971, SiteID: "sv-momlover", StudioName: "MomLover"},
	{CollectionID: 61071, SiteID: "sv-mommysgirl", StudioName: "MommysGirl"},
	{CollectionID: 112341, SiteID: "sv-momsboytoy", StudioName: "MomsBoyToy"},
	{CollectionID: 65721, SiteID: "sv-momslickteens", StudioName: "MomsLickTeens"},
	{CollectionID: 60251, SiteID: "sv-momsteachsex", StudioName: "MomsTeachSex"},
	{CollectionID: 78361, SiteID: "sv-momswap", StudioName: "MomSwap"},
	{CollectionID: 59631, SiteID: "sv-momswithboys", StudioName: "MomsWithBoys"},
	{CollectionID: 112321, SiteID: "sv-momwantstobreed", StudioName: "MomWantsToBreed"},
	{CollectionID: 59091, SiteID: "sv-momxxx", StudioName: "MomXXX"},
	{CollectionID: 117061, SiteID: "sv-moneyshotme", StudioName: "MoneyShotMe"},
	{CollectionID: 65791, SiteID: "sv-monstercurves", StudioName: "MonsterCurves"},
	{CollectionID: 78461, SiteID: "sv-monstermales", StudioName: "MonsterMales"},
	{CollectionID: 65371, SiteID: "sv-monstersofcock", StudioName: "MonstersOfCock"},
	{CollectionID: 69861, SiteID: "sv-monstersofjizz", StudioName: "MonstersOfJizz"},
	{CollectionID: 81651, SiteID: "sv-morepov", StudioName: "MorePOV"},
	{CollectionID: 118911, SiteID: "sv-movieprojectxxx", StudioName: "MovieProjectXXX"},
	{CollectionID: 66461, SiteID: "sv-mranal", StudioName: "MrAnal"},
	{CollectionID: 72031, SiteID: "sv-mrluckypov", StudioName: "MrLuckyPOV"},
	{CollectionID: 64011, SiteID: "sv-mrpov", StudioName: "MrPOV"},
	{CollectionID: 71561, SiteID: "sv-mugurporn", StudioName: "MugurPorn"},
	{CollectionID: 73271, SiteID: "sv-mustnotfap", StudioName: "MustNotFap"},
	{CollectionID: 72271, SiteID: "sv-my18teens", StudioName: "My18Teens"},
	{CollectionID: 73871, SiteID: "sv-myasianslut", StudioName: "MyAsianSlut"},
	{CollectionID: 58201, SiteID: "sv-mydirtyhobby", StudioName: "MyDirtyHobby"},
	{CollectionID: 66441, SiteID: "sv-mydirtymaid", StudioName: "MyDirtyMaid"},
	{CollectionID: 77991, SiteID: "sv-mydirtynovels", StudioName: "MyDirtyNovels"},
	{CollectionID: 67991, SiteID: "sv-myfamilypies", StudioName: "MyFamilyPies"},
	{CollectionID: 61421, SiteID: "sv-myfriendshotmom", StudioName: "MyFriendsHotMom"},
	{CollectionID: 57801, SiteID: "sv-mygf", StudioName: "MyGF"},
	{CollectionID: 67261, SiteID: "sv-mylifeinmiami", StudioName: "MyLifeInMiami"},
	{CollectionID: 76731, SiteID: "sv-mymilfz", StudioName: "MyMilfz"},
	{CollectionID: 64381, SiteID: "sv-mymomsfuckingblackzilla", StudioName: "MyMomsFuckingBlackzilla"},
	{CollectionID: 70371, SiteID: "sv-mynaughtyalbum", StudioName: "MyNaughtyAlbum"},
	{CollectionID: 62511, SiteID: "sv-mypervyfamily", StudioName: "MyPervyFamily"},
	{CollectionID: 68141, SiteID: "sv-mypornfamily", StudioName: "MyPornFamily"},
	{CollectionID: 116511, SiteID: "sv-mypovfam", StudioName: "MyPOVFam"},
	{CollectionID: 75181, SiteID: "sv-mytinywish", StudioName: "MyTinyWish"},
	{CollectionID: 61851, SiteID: "sv-myveryfirsttime", StudioName: "MyVeryFirstTime"},
	{CollectionID: 67171, SiteID: "sv-nannyspy", StudioName: "NannySpy"},
	{CollectionID: 68961, SiteID: "sv-nastybeaver", StudioName: "NastyBeaver"},
	{CollectionID: 78921, SiteID: "sv-nastysenior", StudioName: "NASTYSENIOR"},
	{CollectionID: 116661, SiteID: "sv-naughtyanalfuck", StudioName: "NaughtyAnalFuck"},
	{CollectionID: 117441, SiteID: "sv-naughtyasianwoman", StudioName: "NaughtyAsianWoman"},
	{CollectionID: 117451, SiteID: "sv-naughtyblackgirls", StudioName: "NaughtyBlackGirls"},
	{CollectionID: 119071, SiteID: "sv-naughtycolombia", StudioName: "NaughtyColombia"},
	{CollectionID: 115041, SiteID: "sv-naughtyjapanesegirls", StudioName: "NaughtyJapaneseGirls"},
	{CollectionID: 117461, SiteID: "sv-naughtylesbiangirls", StudioName: "NaughtyLesbianGirls"},
	{CollectionID: 116671, SiteID: "sv-naughtyoldwomen", StudioName: "NaughtyOldWomen"},
	{CollectionID: 99301, SiteID: "sv-nerdpervert", StudioName: "NerdPervert"},
	{CollectionID: 63521, SiteID: "sv-netgirl", StudioName: "NetGirl"},
	{CollectionID: 56991, SiteID: "sv-netvideogirls", StudioName: "NetVideoGirls"},
	{CollectionID: 72121, SiteID: "sv-newmfx", StudioName: "NewMFX"},
	{CollectionID: 58711, SiteID: "sv-newsensations", StudioName: "NewSensations"},
	{CollectionID: 66831, SiteID: "sv-nfbusty", StudioName: "NFBusty"},
	{CollectionID: 73491, SiteID: "sv-nicheparade", StudioName: "NicheParade"},
	{CollectionID: 64841, SiteID: "sv-noboring", StudioName: "NoBoring"},
	{CollectionID: 114731, SiteID: "sv-nopantiestv", StudioName: "NoPantiesTV"},
	{CollectionID: 59021, SiteID: "sv-nubilefilms", StudioName: "NubileFilms"},
	{CollectionID: 77351, SiteID: "sv-nudeyogaporn", StudioName: "NudeYogaPorn"},
	{CollectionID: 56981, SiteID: "sv-nurumassage", StudioName: "NuruMassage"},
	{CollectionID: 59781, SiteID: "sv-nworship", StudioName: "NWorship"},
	{CollectionID: 67251, SiteID: "sv-nylonfeetlove", StudioName: "NylonFeetLove"},
	{CollectionID: 64251, SiteID: "sv-nylonup", StudioName: "NylonUp"},
	{CollectionID: 79071, SiteID: "sv-oblackgirls", StudioName: "OBlackGirls"},
	{CollectionID: 79041, SiteID: "sv-oblowjobs", StudioName: "OBlowjobs"},
	{CollectionID: 79281, SiteID: "sv-officepov", StudioName: "OfficePOV"},
	{CollectionID: 78221, SiteID: "sv-oldbangsyoung", StudioName: "OldBangsYoung"},
	{CollectionID: 61251, SiteID: "sv-oldgoesyoung", StudioName: "OldGoesYoung"},
	{CollectionID: 58951, SiteID: "sv-oldnanny", StudioName: "OldNanny"},
	{CollectionID: 68151, SiteID: "sv-oldpigs", StudioName: "OldPigs"},
	{CollectionID: 78931, SiteID: "sv-oldstyleporn", StudioName: "OLDSTYLEPORN"},
	{CollectionID: 116991, SiteID: "sv-onlybbc", StudioName: "OnlyBBC"},
	{CollectionID: 77311, SiteID: "sv-onlycougars", StudioName: "OnlyCougars"},
	{CollectionID: 77391, SiteID: "sv-onlytaboo", StudioName: "OnlyTaboo"},
	{CollectionID: 59171, SiteID: "sv-onlyteenblowjobs", StudioName: "OnlyTeenBlowjobs"},
	{CollectionID: 70381, SiteID: "sv-operacionlimpieza", StudioName: "OperacionLimpieza"},
	{CollectionID: 118941, SiteID: "sv-orrangemedia", StudioName: "OrrangeMedia"},
	{CollectionID: 59031, SiteID: "sv-outofthefamily", StudioName: "OutOfTheFamily"},
	{CollectionID: 58371, SiteID: "sv-over40handjobs", StudioName: "Over40Handjobs"},
	{CollectionID: 78701, SiteID: "sv-pacopaco", StudioName: "PacoPaco"},
	{CollectionID: 73211, SiteID: "sv-pantyhoseacademy", StudioName: "PantyhoseAcademy"},
	{CollectionID: 67881, SiteID: "sv-papayakings", StudioName: "PapayaKings"},
	{CollectionID: 66701, SiteID: "sv-partyofthree", StudioName: "PartyOfThree"},
	{CollectionID: 58261, SiteID: "sv-passionhd", StudioName: "Passion-HD"},
	{CollectionID: 79561, SiteID: "sv-passionsonly", StudioName: "PassionsOnly"},
	{CollectionID: 66471, SiteID: "sv-pawg", StudioName: "PAWG"},
	{CollectionID: 79241, SiteID: "sv-pawged", StudioName: "PAWGED"},
	{CollectionID: 69631, SiteID: "sv-peccatriciproduzioni", StudioName: "PeccatriciProduzioni"},
	{CollectionID: 71841, SiteID: "sv-peepleak", StudioName: "PeepLeak"},
	{CollectionID: 64341, SiteID: "sv-pennypaxlive", StudioName: "PennyPaxLive"},
	{CollectionID: 71521, SiteID: "sv-pepeporn", StudioName: "PepePorn"},
	{CollectionID: 68381, SiteID: "sv-perfectgirls", StudioName: "PerfectGirls"},
	{CollectionID: 61551, SiteID: "sv-pervcity", StudioName: "PervCity"},
	{CollectionID: 77701, SiteID: "sv-pervdoctor", StudioName: "PervDoctor"},
	{CollectionID: 100711, SiteID: "sv-pervertclips", StudioName: "PervertClips"},
	{CollectionID: 116501, SiteID: "sv-pervertedpov", StudioName: "PervertedPOV"},
	{CollectionID: 71951, SiteID: "sv-pervfect", StudioName: "Pervfect"},
	{CollectionID: 118011, SiteID: "sv-pervmilfsandteens", StudioName: "PervMilfsAndTeens"},
	{CollectionID: 67861, SiteID: "sv-pervmom", StudioName: "PervMom"},
	{CollectionID: 76851, SiteID: "sv-peterskingdom", StudioName: "PetersKingdom"},
	{CollectionID: 60751, SiteID: "sv-petite18", StudioName: "Petite18"},
	{CollectionID: 61471, SiteID: "sv-petitehdporn", StudioName: "PetiteHDPorn"},
	{CollectionID: 79251, SiteID: "sv-petitepov", StudioName: "PetitePOV"},
	{CollectionID: 62631, SiteID: "sv-philavise", StudioName: "Philavise"},
	{CollectionID: 74271, SiteID: "sv-pinkkittyvideo", StudioName: "PinkKittyVideo"},
	{CollectionID: 70391, SiteID: "sv-pinupsex", StudioName: "PinUpSex"},
	{CollectionID: 74751, SiteID: "sv-pissingaustria", StudioName: "PissingAustria"},
	{CollectionID: 75741, SiteID: "sv-pissinghd", StudioName: "PissingHD"},
	{CollectionID: 65111, SiteID: "sv-plumperd", StudioName: "Plumperd"},
	{CollectionID: 69421, SiteID: "sv-plushiestv", StudioName: "PlushiesTV"},
	{CollectionID: 77711, SiteID: "sv-pooksi", StudioName: "Pooksi"},
	{CollectionID: 117031, SiteID: "sv-porkvendors", StudioName: "PorkVendors"},
	{CollectionID: 76771, SiteID: "sv-pornamazing", StudioName: "PornAmazing"},
	{CollectionID: 78791, SiteID: "sv-pornartx", StudioName: "PORNARTX"},
	{CollectionID: 64581, SiteID: "sv-porncentro", StudioName: "Porncentro"},
	{CollectionID: 66381, SiteID: "sv-pornditos", StudioName: "Pornditos"},
	{CollectionID: 70401, SiteID: "sv-porndoepedia", StudioName: "PornDoePedia"},
	{CollectionID: 63211, SiteID: "sv-pornfidelity", StudioName: "Pornfidelity"},
	{CollectionID: 61751, SiteID: "sv-porngoespro", StudioName: "PornGoesPro"},
	{CollectionID: 70611, SiteID: "sv-porninparisclub", StudioName: "PornInParisClub"},
	{CollectionID: 60631, SiteID: "sv-pornlandvideos", StudioName: "PornlandVideos"},
	{CollectionID: 74461, SiteID: "sv-pornmuschimovie", StudioName: "PornmuschiMovie"},
	{CollectionID: 76981, SiteID: "sv-pornovatas", StudioName: "PorNovatas"},
	{CollectionID: 58111, SiteID: "sv-pornpros", StudioName: "PornPros"},
	{CollectionID: 72621, SiteID: "sv-pornstarclassics", StudioName: "PornstarClassics"},
	{CollectionID: 77661, SiteID: "sv-pornstarlegends", StudioName: "PornstarLegends"},
	{CollectionID: 59211, SiteID: "sv-pornstarplatinum", StudioName: "PornstarPlatinum"},
	{CollectionID: 66611, SiteID: "sv-pornstarspa", StudioName: "PornStarSpa"},
	{CollectionID: 61761, SiteID: "sv-pornstartease", StudioName: "PornstarTease"},
	{CollectionID: 77231, SiteID: "sv-porntolove", StudioName: "PornToLove"},
	{CollectionID: 62931, SiteID: "sv-porntugal", StudioName: "Porntugal"},
	{CollectionID: 69281, SiteID: "sv-pornvalleygirls", StudioName: "PornValleyGirls"},
	{CollectionID: 63131, SiteID: "sv-portagloryhole", StudioName: "PortaGloryHole"},
	{CollectionID: 68241, SiteID: "sv-povattack", StudioName: "POVAttack"},
	{CollectionID: 60241, SiteID: "sv-povd", StudioName: "POVD"},
	{CollectionID: 71161, SiteID: "sv-povmania", StudioName: "POVMania"},
	{CollectionID: 76741, SiteID: "sv-povmasters", StudioName: "POVMasters"},
	{CollectionID: 73681, SiteID: "sv-povmovies", StudioName: "POVMovies"},
	{CollectionID: 77931, SiteID: "sv-povperv", StudioName: "POVPerv"},
	{CollectionID: 72471, SiteID: "sv-povpickups", StudioName: "POVPickups"},
	{CollectionID: 61401, SiteID: "sv-povtrain", StudioName: "POVTrain"},
	{CollectionID: 65961, SiteID: "sv-preggolovers", StudioName: "PreggoLovers"},
	{CollectionID: 65301, SiteID: "sv-premiumbukkake", StudioName: "PremiumBukkake"},
	{CollectionID: 70721, SiteID: "sv-primalscompetitivesexwrestling", StudioName: "PrimalsCompetitiveSexWrestling"},
	{CollectionID: 70741, SiteID: "sv-primalsdarkfantasies", StudioName: "PrimalsDarkFantasies"},
	{CollectionID: 71041, SiteID: "sv-primalsedginghandjobsandblowjobs", StudioName: "PrimalsEdgingHandjobsandBlowjobs"},
	{CollectionID: 70691, SiteID: "sv-primalsfootjobfantasies", StudioName: "PrimalsFootjobFantasies"},
	{CollectionID: 70701, SiteID: "sv-primalshandjobdomination", StudioName: "PrimalsHandjobDomination"},
	{CollectionID: 70711, SiteID: "sv-primalsmentaldomination", StudioName: "PrimalsMentalDomination"},
	{CollectionID: 69021, SiteID: "sv-princesscum", StudioName: "PrincessCum"},
	{CollectionID: 60761, SiteID: "sv-privatesociety", StudioName: "PrivateSociety"},
	{CollectionID: 68481, SiteID: "sv-producersfun", StudioName: "ProducersFun"},
	{CollectionID: 59011, SiteID: "sv-publicagent", StudioName: "PublicAgent"},
	{CollectionID: 78111, SiteID: "sv-publicsexdate", StudioName: "PublicSexDate"},
	{CollectionID: 68951, SiteID: "sv-puffyflix", StudioName: "PuffyFlix"},
	{CollectionID: 68911, SiteID: "sv-puffynetwork", StudioName: "PuffyNetwork"},
	{CollectionID: 68771, SiteID: "sv-purebbw", StudioName: "Pure-BBW"},
	{CollectionID: 63511, SiteID: "sv-pure18", StudioName: "Pure18"},
	{CollectionID: 70651, SiteID: "sv-purgatoryx", StudioName: "PurgatoryX"},
	{CollectionID: 80061, SiteID: "sv-quenteclub", StudioName: "QuenteClub"},
	{CollectionID: 70411, SiteID: "sv-questfororgasm", StudioName: "QuestForOrgasm"},
	{CollectionID: 70621, SiteID: "sv-rammed", StudioName: "Rammed"},
	{CollectionID: 68901, SiteID: "sv-rawattack", StudioName: "RawAttack"},
	{CollectionID: 77441, SiteID: "sv-rawwhitemeat", StudioName: "RawWhiteMeat"},
	{CollectionID: 65831, SiteID: "sv-realagentxxx", StudioName: "RealAgentXXX"},
	{CollectionID: 77151, SiteID: "sv-realanalstories", StudioName: "RealAnalStories"},
	{CollectionID: 72451, SiteID: "sv-realbikinigirls", StudioName: "RealBikiniGirls"},
	{CollectionID: 68841, SiteID: "sv-realdirtyvideos", StudioName: "RealDirtyVideos"},
	{CollectionID: 57001, SiteID: "sv-realexgirlfriends", StudioName: "RealExGirlfriends"},
	{CollectionID: 61611, SiteID: "sv-realgangbangs", StudioName: "RealGangBangs"},
	{CollectionID: 116731, SiteID: "sv-realgirlsfuck", StudioName: "RealGirlsFuck"},
	{CollectionID: 68251, SiteID: "sv-realhomemade", StudioName: "RealHomemade"},
	{CollectionID: 58821, SiteID: "sv-realityjunkies", StudioName: "RealityJunkies"},
	{CollectionID: 64651, SiteID: "sv-realitylovers", StudioName: "RealityLovers"},
	{CollectionID: 72361, SiteID: "sv-realsensual", StudioName: "RealSensual"},
	{CollectionID: 119955, SiteID: "sv-realvidsxxx", StudioName: "RealVidsXXX"},
	{CollectionID: 65681, SiteID: "sv-redxxx", StudioName: "Red-XXX"},
	{CollectionID: 68291, SiteID: "sv-redlighthd", StudioName: "Redlight-HD"},
	{CollectionID: 57281, SiteID: "sv-redlightsextrips", StudioName: "RedLightSexTrips"},
	{CollectionID: 70421, SiteID: "sv-reifeswinger", StudioName: "ReifeSwinger"},
	{CollectionID: 70431, SiteID: "sv-relaxxxed", StudioName: "Relaxxxed"},
	{CollectionID: 73661, SiteID: "sv-restrictingropes", StudioName: "RestrictingRopes"},
	{CollectionID: 117361, SiteID: "sv-riggsfilms", StudioName: "RiggsFilms"},
	{CollectionID: 75321, SiteID: "sv-rim4k", StudioName: "Rim4K"},
	{CollectionID: 77561, SiteID: "sv-rimteens", StudioName: "RimTeens"},
	{CollectionID: 70671, SiteID: "sv-roadsidexxx", StudioName: "RoadsideXXX"},
	{CollectionID: 67001, SiteID: "sv-rockspornchix", StudioName: "RocksPornChix"},
	{CollectionID: 72631, SiteID: "sv-romanvideo", StudioName: "RomanVideo"},
	{CollectionID: 66851, SiteID: "sv-romemajor", StudioName: "RomeMajor"},
	{CollectionID: 63141, SiteID: "sv-roundandbrown", StudioName: "RoundAndBrown"},
	{CollectionID: 62551, SiteID: "sv-ryanneredd", StudioName: "RyAnneRedd"},
	{CollectionID: 61791, SiteID: "sv-sarajay", StudioName: "SaraJay"},
	{CollectionID: 70111, SiteID: "sv-scamangels", StudioName: "ScamAngels"},
	{CollectionID: 70441, SiteID: "sv-scambistimaturi", StudioName: "ScambistiMaturi"},
	{CollectionID: 112531, SiteID: "sv-scifix", StudioName: "Scifi-X"},
	{CollectionID: 73571, SiteID: "sv-screwmetoo", StudioName: "ScrewMeToo"},
	{CollectionID: 63731, SiteID: "sv-seancody", StudioName: "SeanCody"},
	{CollectionID: 58361, SiteID: "sv-seemomsuck", StudioName: "SeeMomSuck"},
	{CollectionID: 77221, SiteID: "sv-sexalltogether", StudioName: "SexAllTogether"},
	{CollectionID: 114901, SiteID: "sv-sexfantasy", StudioName: "SexFantasy"},
	{CollectionID: 60331, SiteID: "sv-sexflexvideo", StudioName: "SexFlexVideo"},
	{CollectionID: 74481, SiteID: "sv-sexgamesprivate", StudioName: "SexGamesPrivate"},
	{CollectionID: 64971, SiteID: "sv-sexplanet", StudioName: "SexPlanet"},
	{CollectionID: 70451, SiteID: "sv-sextapegermany", StudioName: "SextapeGermany"},
	{CollectionID: 78601, SiteID: "sv-sexybuurvrouw", StudioName: "SEXYBUURVROUW"},
	{CollectionID: 78451, SiteID: "sv-sexycuckold", StudioName: "SexyCuckold"},
	{CollectionID: 65321, SiteID: "sv-sexyninarivera", StudioName: "SexyNinaRivera"},
	{CollectionID: 69191, SiteID: "sv-shaggingmoms", StudioName: "ShaggingMoms"},
	{CollectionID: 57751, SiteID: "sv-shakethesnake", StudioName: "ShakeTheSnake"},
	{CollectionID: 78501, SiteID: "sv-shame4k", StudioName: "Shame4K"},
	{CollectionID: 79601, SiteID: "sv-shanedieselxxx", StudioName: "ShaneDieselXXX"},
	{CollectionID: 64541, SiteID: "sv-sheenaryderxxx", StudioName: "SheenaRyderXXX"},
	{CollectionID: 79361, SiteID: "sv-sheerandlace", StudioName: "SheerAndLace"},
	{CollectionID: 69051, SiteID: "sv-shelovesherman", StudioName: "SheLovesHerMan"},
	{CollectionID: 61271, SiteID: "sv-shemadeuslesbians", StudioName: "SheMadeUsLesbians"},
	{CollectionID: 68261, SiteID: "sv-shemaleworld", StudioName: "ShemaleWorld"},
	{CollectionID: 63631, SiteID: "sv-shesbrandnew", StudioName: "ShesBrandNew"},
	{CollectionID: 75111, SiteID: "sv-sheseducedme", StudioName: "SheSeducedMe"},
	{CollectionID: 64731, SiteID: "sv-shewillcheat", StudioName: "SheWillCheat"},
	{CollectionID: 64791, SiteID: "sv-shoplyfter", StudioName: "ShopLyfter"},
	{CollectionID: 70191, SiteID: "sv-shotherfirst", StudioName: "ShotHerFirst"},
	{CollectionID: 58761, SiteID: "sv-shyangela", StudioName: "ShyAngela"},
	{CollectionID: 64801, SiteID: "sv-simplyanal", StudioName: "SimplyAnal"},
	{CollectionID: 69981, SiteID: "sv-simplysmut", StudioName: "SimplySmut"},
	{CollectionID: 79961, SiteID: "sv-sinfulfeet", StudioName: "SinfulFeet"},
	{CollectionID: 61881, SiteID: "sv-sinfulsolos", StudioName: "SinfulSolos"},
	{CollectionID: 64601, SiteID: "sv-sinfulxxx", StudioName: "SinfulXXX"},
	{CollectionID: 119831, SiteID: "sv-sinnerxxx", StudioName: "SinnerXXX"},
	{CollectionID: 113551, SiteID: "sv-sinnsagexxx", StudioName: "SinnSageXXX"},
	{CollectionID: 62941, SiteID: "sv-sislovesme", StudioName: "SisLovesMe"},
	{CollectionID: 75931, SiteID: "sv-siswantsit", StudioName: "SisWantsIt"},
	{CollectionID: 74361, SiteID: "sv-skinomaxhd", StudioName: "SkinoMaxHD"},
	{CollectionID: 78561, SiteID: "sv-skinzerotica", StudioName: "SkinzErotica"},
	{CollectionID: 74411, SiteID: "sv-slim4k", StudioName: "Slim4K"},
	{CollectionID: 76531, SiteID: "sv-slutinspection", StudioName: "SlutInspection"},
	{CollectionID: 79571, SiteID: "sv-slutsaroundtown", StudioName: "SlutsAroundTown"},
	{CollectionID: 75381, SiteID: "sv-sluttyhousewives", StudioName: "SluttyHousewives"},
	{CollectionID: 77141, SiteID: "sv-sluttymilf", StudioName: "SluttyMilf"},
	{CollectionID: 78311, SiteID: "sv-smallfirmboobs", StudioName: "SmallFirmBoobs"},
	{CollectionID: 59571, SiteID: "sv-smashpictures", StudioName: "SmashPictures"},
	{CollectionID: 66121, SiteID: "sv-smutbuttxxx", StudioName: "SmutButtXXX"},
	{CollectionID: 72551, SiteID: "sv-socialmediacelebs", StudioName: "SocialMediaCelebs"},
	{CollectionID: 60651, SiteID: "sv-sologirlsmania", StudioName: "SoloGirlsMania"},
	{CollectionID: 79891, SiteID: "sv-spanishmorbo", StudioName: "SpanishMorbo"},
	{CollectionID: 69601, SiteID: "sv-spankmonster", StudioName: "SpankMonster"},
	{CollectionID: 65341, SiteID: "sv-spicemysexlife", StudioName: "SpiceMySexLife"},
	{CollectionID: 67921, SiteID: "sv-spicylab", StudioName: "SpicyLab"},
	{CollectionID: 61771, SiteID: "sv-spizoo", StudioName: "Spizoo"},
	{CollectionID: 69711, SiteID: "sv-spizoo4k", StudioName: "Spizoo4K"},
	{CollectionID: 61281, SiteID: "sv-spoiledvirgins", StudioName: "SpoiledVirgins"},
	{CollectionID: 79871, SiteID: "sv-springthomas", StudioName: "SpringThomas"},
	{CollectionID: 65711, SiteID: "sv-spyfam", StudioName: "SpyFam"},
	{CollectionID: 75701, SiteID: "sv-squirted", StudioName: "Squirted"},
	{CollectionID: 73771, SiteID: "sv-squirtingfun", StudioName: "SquirtingFun"},
	{CollectionID: 66421, SiteID: "sv-stepmomvideos", StudioName: "StepMomVideos"},
	{CollectionID: 75091, SiteID: "sv-stepmomwithboys", StudioName: "StepmomWithBoys"},
	{CollectionID: 78041, SiteID: "sv-steppov", StudioName: "StepPOV"},
	{CollectionID: 62481, SiteID: "sv-stepsiblingscaught", StudioName: "StepSiblingsCaught"},
	{CollectionID: 75991, SiteID: "sv-stevenshame", StudioName: "StevenShame"},
	{CollectionID: 79821, SiteID: "sv-straightbutcurious", StudioName: "StraightButCurious"},
	{CollectionID: 78121, SiteID: "sv-straightintheass", StudioName: "StraightInTheAss"},
	{CollectionID: 67011, SiteID: "sv-straighttoanal", StudioName: "StraightToAnal"},
	{CollectionID: 58721, SiteID: "sv-straplezz", StudioName: "Straplezz"},
	{CollectionID: 65801, SiteID: "sv-streetblowjobs", StudioName: "StreetBlowJobs"},
	{CollectionID: 72091, SiteID: "sv-submissed", StudioName: "Submissed"},
	{CollectionID: 77831, SiteID: "sv-submissivex", StudioName: "SubmissiveX"},
	{CollectionID: 78811, SiteID: "sv-suddenanalstories", StudioName: "SUDDENANALSTORIES"},
	{CollectionID: 69561, SiteID: "sv-sugardaddyporn", StudioName: "SugarDaddyPorn"},
	{CollectionID: 61951, SiteID: "sv-sukmydick", StudioName: "SukMyDick"},
	{CollectionID: 76051, SiteID: "sv-summersinners", StudioName: "SummerSinners"},
	{CollectionID: 65671, SiteID: "sv-superhotfilms", StudioName: "SuperHotFilms"},
	{CollectionID: 78091, SiteID: "sv-sventertainment", StudioName: "SVEntertainment"},
	{CollectionID: 64961, SiteID: "sv-swallowed", StudioName: "Swallowed"},
	{CollectionID: 82011, SiteID: "sv-swappz", StudioName: "Swappz"},
	{CollectionID: 113731, SiteID: "sv-sweetass", StudioName: "SweetAss"},
	{CollectionID: 62361, SiteID: "sv-sweetfemdom", StudioName: "SweetFemdom"},
	{CollectionID: 58831, SiteID: "sv-sweetheartvideo", StudioName: "SweetheartVideo"},
	{CollectionID: 72821, SiteID: "sv-sweethunnybunny", StudioName: "SweetHunnyBunny"},
	{CollectionID: 58841, SiteID: "sv-sweetsinner", StudioName: "SweetSinner"},
	{CollectionID: 74511, SiteID: "sv-sweetthing", StudioName: "SweetThing"},
	{CollectionID: 67091, SiteID: "sv-swhores", StudioName: "Swhores"},
	{CollectionID: 73351, SiteID: "sv-swingerblogxxx", StudioName: "Swinger-BlogXXX"},
	{CollectionID: 74701, SiteID: "sv-tabuworld", StudioName: "TabuWorld"},
	{CollectionID: 119351, SiteID: "sv-tadpolexstudio", StudioName: "TadpolexStudio"},
	{CollectionID: 64141, SiteID: "sv-tarantinoxxx", StudioName: "TarantinoXXX"},
	{CollectionID: 62271, SiteID: "sv-tealconrad", StudioName: "TealConrad"},
	{CollectionID: 58091, SiteID: "sv-teamskeet", StudioName: "TeamSkeet"},
	{CollectionID: 64181, SiteID: "sv-teasepov", StudioName: "TeasePOV"},
	{CollectionID: 66101, SiteID: "sv-teasingangels", StudioName: "TeasingAngels"},
	{CollectionID: 57061, SiteID: "sv-teenbff", StudioName: "TeenBFF"},
	{CollectionID: 91851, SiteID: "sv-teendreams", StudioName: "TeenDreams"},
	{CollectionID: 63201, SiteID: "sv-teenfidelity", StudioName: "TeenFidelity"},
	{CollectionID: 58321, SiteID: "sv-teenmegaworld", StudioName: "TeenMegaWorld"},
	{CollectionID: 65091, SiteID: "sv-teenrs", StudioName: "Teenrs"},
	{CollectionID: 78201, SiteID: "sv-teenslikeithard", StudioName: "TeensLikeItHard"},
	{CollectionID: 113741, SiteID: "sv-teenssins", StudioName: "TeensSins"},
	{CollectionID: 77011, SiteID: "sv-teensvisions", StudioName: "TeensVisions"},
	{CollectionID: 59101, SiteID: "sv-teentugs", StudioName: "TeenTugs"},
	{CollectionID: 76781, SiteID: "sv-teenxxxstories", StudioName: "TeenXXXStories"},
	{CollectionID: 79691, SiteID: "sv-teenytaboo", StudioName: "TeenyTaboo"},
	{CollectionID: 78611, SiteID: "sv-tenshigao", StudioName: "Tenshigao"},
	{CollectionID: 57731, SiteID: "sv-terapatrick", StudioName: "TeraPatrick"},
	{CollectionID: 70981, SiteID: "sv-terrorxxx", StudioName: "TerrorXXX"},
	{CollectionID: 76061, SiteID: "sv-thaiurge", StudioName: "ThaiUrge"},
	{CollectionID: 106111, SiteID: "sv-thatsitcomshow", StudioName: "ThatSitcomShow"},
	{CollectionID: 79211, SiteID: "sv-thebestofthebest", StudioName: "TheBestoftheBest"},
	{CollectionID: 64021, SiteID: "sv-thedicksuckers", StudioName: "TheDickSuckers"},
	{CollectionID: 58381, SiteID: "sv-thefemaleorgasm", StudioName: "TheFemaleOrgasm"},
	{CollectionID: 74661, SiteID: "sv-thejerkoffgames", StudioName: "TheJerkoffGames"},
	{CollectionID: 64681, SiteID: "sv-thelesbianexperience", StudioName: "TheLesbianExperience"},
	{CollectionID: 76401, SiteID: "sv-thelexierosspermshow", StudioName: "TheLexiErosSpermShow"},
	{CollectionID: 78641, SiteID: "sv-thepovclub", StudioName: "ThePOVClub"},
	{CollectionID: 61781, SiteID: "sv-thestripperexperience", StudioName: "TheStripperExperience"},
	{CollectionID: 65511, SiteID: "sv-thevenusgirls", StudioName: "TheVenusGirls"},
	{CollectionID: 70121, SiteID: "sv-thewhiteboxxx", StudioName: "TheWhiteBoxxx"},
	{CollectionID: 76951, SiteID: "sv-thick", StudioName: "Thick"},
	{CollectionID: 70211, SiteID: "sv-thisiscollege", StudioName: "ThisIsCollege"},
	{CollectionID: 78401, SiteID: "sv-threesome4ever", StudioName: "Threesome4ever"},
	{CollectionID: 59181, SiteID: "sv-throated", StudioName: "Throated"},
	{CollectionID: 106191, SiteID: "sv-thundercock", StudioName: "Thundercock"},
	{CollectionID: 60801, SiteID: "sv-tiny4k", StudioName: "Tiny4K"},
	{CollectionID: 79731, SiteID: "sv-tmwpov", StudioName: "TMWPOV"},
	{CollectionID: 64301, SiteID: "sv-tmwvrnet", StudioName: "TMWVRNet"},
	{CollectionID: 61491, SiteID: "sv-tonightsgirlfriend", StudioName: "TonightsGirlfriend"},
	{CollectionID: 58971, SiteID: "sv-topwebmodels", StudioName: "TopWebModels"},
	{CollectionID: 69591, SiteID: "sv-touchmywife", StudioName: "TouchMyWife"},
	{CollectionID: 60621, SiteID: "sv-touchthebodyhd", StudioName: "TouchTheBodyHD"},
	{CollectionID: 69611, SiteID: "sv-toughlovex", StudioName: "ToughLoveX"},
	{CollectionID: 64081, SiteID: "sv-trannyaddiction", StudioName: "TrannyAddiction"},
	{CollectionID: 63001, SiteID: "sv-translove", StudioName: "TransLove"},
	{CollectionID: 70541, SiteID: "sv-trickery", StudioName: "Trickery"},
	{CollectionID: 61291, SiteID: "sv-trickyoldteacher", StudioName: "TrickyOldTeacher"},
	{CollectionID: 75761, SiteID: "sv-tripforfuck", StudioName: "TripForFuck"},
	{CollectionID: 70871, SiteID: "sv-trueamateurs", StudioName: "TrueAmateurs"},
	{CollectionID: 68541, SiteID: "sv-trueanal", StudioName: "TrueAnal"},
	{CollectionID: 59201, SiteID: "sv-tryanalfisting", StudioName: "TryAnalFisting"},
	{CollectionID: 66711, SiteID: "sv-tugjobs", StudioName: "TugJobs"},
	{CollectionID: 62041, SiteID: "sv-tushy", StudioName: "Tushy"},
	{CollectionID: 70561, SiteID: "sv-tushyraw", StudioName: "TushyRaw"},
	{CollectionID: 63371, SiteID: "sv-tutorhim", StudioName: "TutorHim"},
	{CollectionID: 113761, SiteID: "sv-twinkpop", StudioName: "TwinkPop"},
	{CollectionID: 75361, SiteID: "sv-uktickling", StudioName: "UKTickling"},
	{CollectionID: 80591, SiteID: "sv-upox", StudioName: "Upox"},
	{CollectionID: 72071, SiteID: "sv-upskirtjerk", StudioName: "UpskirtJerk"},
	{CollectionID: 74321, SiteID: "sv-userdategerman", StudioName: "USERDATEGerman"},
	{CollectionID: 74331, SiteID: "sv-userdateinternational", StudioName: "USERDATEInternational"},
	{CollectionID: 62131, SiteID: "sv-vangoren", StudioName: "VanGoren"},
	{CollectionID: 64551, SiteID: "sv-vannahsterling", StudioName: "VannahSterling"},
	{CollectionID: 62871, SiteID: "sv-velvetecstasy", StudioName: "VelvetEcstasy"},
	{CollectionID: 60971, SiteID: "sv-vickyathome", StudioName: "VickyAtHome"},
	{CollectionID: 75621, SiteID: "sv-violettheteenagesucker", StudioName: "VioletTheTeenageSucker"},
	{CollectionID: 71191, SiteID: "sv-vip4k", StudioName: "VIP4K"},
	{CollectionID: 60011, SiteID: "sv-vipissy", StudioName: "VIPissy"},
	{CollectionID: 70891, SiteID: "sv-vipsexvault", StudioName: "VipSexVault"},
	{CollectionID: 65181, SiteID: "sv-virtualxporn", StudioName: "VirtualXPorn"},
	{CollectionID: 64331, SiteID: "sv-vixen", StudioName: "Vixen"},
	{CollectionID: 69721, SiteID: "sv-vlogxxx", StudioName: "VLogXXX"},
	{CollectionID: 73601, SiteID: "sv-vrallure", StudioName: "VRAllure"},
	{CollectionID: 65811, SiteID: "sv-vrcosplayx", StudioName: "VRCosplayX"},
	{CollectionID: 65351, SiteID: "sv-vrhush", StudioName: "VRHush"},
	{CollectionID: 69431, SiteID: "sv-vrlatina", StudioName: "VRLatina"},
	{CollectionID: 65041, SiteID: "sv-vrsexperience", StudioName: "VRSexperience"},
	{CollectionID: 117321, SiteID: "sv-vrspy", StudioName: "VRSpy"},
	{CollectionID: 58531, SiteID: "sv-vubado", StudioName: "Vubado"},
	{CollectionID: 63781, SiteID: "sv-vubadonevest", StudioName: "Vubado Nevest"},
	{CollectionID: 62901, SiteID: "sv-vubadoacc", StudioName: "VubadoACC"},
	{CollectionID: 62981, SiteID: "sv-vubadoacd", StudioName: "VubadoACD"},
	{CollectionID: 62991, SiteID: "sv-vubadoadula", StudioName: "VubadoAdula"},
	{CollectionID: 62911, SiteID: "sv-vubadoblack", StudioName: "VubadoBlack"},
	{CollectionID: 70921, SiteID: "sv-vubadoeuro", StudioName: "VubadoEuro"},
	{CollectionID: 62921, SiteID: "sv-vubadojapanese", StudioName: "VubadoJapanese"},
	{CollectionID: 71321, SiteID: "sv-wankitnow", StudioName: "WankItNow"},
	{CollectionID: 72131, SiteID: "sv-wankitnowvr", StudioName: "WankItNowVR"},
	{CollectionID: 64131, SiteID: "sv-weare321", StudioName: "WeAre321"},
	{CollectionID: 59391, SiteID: "sv-webyoung", StudioName: "WebYoung"},
	{CollectionID: 58431, SiteID: "sv-weliketosuck", StudioName: "WeLikeToSuck"},
	{CollectionID: 58941, SiteID: "sv-westcoastproductions", StudioName: "WestCoastProductions"},
	{CollectionID: 58781, SiteID: "sv-wetandpissy", StudioName: "WetandPissy"},
	{CollectionID: 56961, SiteID: "sv-wetandpuffy", StudioName: "WetandPuffy"},
	{CollectionID: 65661, SiteID: "sv-wetwetgirls", StudioName: "WetWetGirls"},
	{CollectionID: 59531, SiteID: "sv-whengirlsplay", StudioName: "WhenGirlsPlay"},
	{CollectionID: 64401, SiteID: "sv-whitezilla", StudioName: "Whitezilla"},
	{CollectionID: 92321, SiteID: "sv-whoresinpublic", StudioName: "WhoresInPublic"},
	{CollectionID: 67111, SiteID: "sv-wildgangbangs", StudioName: "WildGangBangs"},
	{CollectionID: 76261, SiteID: "sv-wolfwagnercom", StudioName: "WolfWagnerCom"},
	{CollectionID: 73431, SiteID: "sv-wolfwagnerlove", StudioName: "WolfWagnerLove"},
	{CollectionID: 77241, SiteID: "sv-wonderfullbigboobs", StudioName: "WonderfullBigboobs"},
	{CollectionID: 68851, SiteID: "sv-worldofasian", StudioName: "WorldOfAsian"},
	{CollectionID: 78801, SiteID: "sv-worldwideamateur", StudioName: "WORLDWIDEAMATEUR"},
	{CollectionID: 67911, SiteID: "sv-wwmamm", StudioName: "WWMAMM"},
	{CollectionID: 59791, SiteID: "sv-xangels", StudioName: "X-Angels"},
	{CollectionID: 117381, SiteID: "sv-xblackhub", StudioName: "XBlackHub"},
	{CollectionID: 70141, SiteID: "sv-xchimera", StudioName: "XChimera"},
	{CollectionID: 65821, SiteID: "sv-xczech", StudioName: "XCzech"},
	{CollectionID: 111851, SiteID: "sv-xekeko", StudioName: "Xekeko"},
	{CollectionID: 73611, SiteID: "sv-xespl", StudioName: "XESPL"},
	{CollectionID: 79681, SiteID: "sv-xprimeuk", StudioName: "XPrimeUK"},
	{CollectionID: 64151, SiteID: "sv-xtime", StudioName: "Xtime"},
	{CollectionID: 114101, SiteID: "sv-xxxbrits", StudioName: "XXXBrits"},
	{CollectionID: 73511, SiteID: "sv-xxxdefeatedxxx", StudioName: "XXXDefeatedXXX"},
	{CollectionID: 114461, SiteID: "sv-xxxjobinterviews", StudioName: "XXXJobInterviews"},
	{CollectionID: 70471, SiteID: "sv-xxxomas", StudioName: "XXXOmas"},
	{CollectionID: 61871, SiteID: "sv-xxxpawn", StudioName: "XXXPawn"},
	{CollectionID: 74471, SiteID: "sv-xxxrealityfuck", StudioName: "XXXRealityFuck"},
	{CollectionID: 70481, SiteID: "sv-xxxshades", StudioName: "XXXShades"},
	{CollectionID: 61301, SiteID: "sv-younganaltryouts", StudioName: "YoungAnalTryouts"},
	{CollectionID: 59451, SiteID: "sv-youngbusty", StudioName: "YoungBusty"},
	{CollectionID: 75251, SiteID: "sv-youngmistress", StudioName: "YoungMistress"},
	{CollectionID: 66191, SiteID: "sv-youngsinner", StudioName: "YoungSinner"},
	{CollectionID: 58511, SiteID: "sv-yungdumbsluts", StudioName: "YungDumbSluts"},
	{CollectionID: 57931, SiteID: "sv-yuriluv", StudioName: "YuriLuv"},
	{CollectionID: 79591, SiteID: "sv-zfilmz", StudioName: "Z-Filmz"},
	{CollectionID: 77691, SiteID: "sv-zerotolerancefilms", StudioName: "ZeroToleranceFilms"},
	{CollectionID: 72101, SiteID: "sv-zexyvr", StudioName: "ZexyVR"},
	{CollectionID: 69751, SiteID: "sv-zizivids", StudioName: "ZiziVids"},
}

var ayloConfig = ayloutil.SiteConfig{
	SiteID:     "spicevids",
	SiteBase:   "https://www.spicevids.com",
	StudioName: "SpiceVids",
	ScenePath:  "scene",
}

var collectionMatchRe = regexp.MustCompile(`spicevids\.com/collection/(\d+)`)

func init() {
	lookup := make(map[int]*collectionScraper, len(collections))
	for _, cfg := range collections {
		ayloCfg := ayloConfig
		ayloCfg.SiteID = cfg.SiteID
		ayloCfg.StudioName = cfg.StudioName
		s := &collectionScraper{
			aylo:   ayloutil.NewScraper(ayloCfg),
			config: cfg,
		}
		scraper.Register(s)
		lookup[cfg.CollectionID] = s
	}
	scraper.Register(&genericScraper{aylo: ayloutil.NewScraper(ayloConfig), lookup: lookup})
}

type collectionScraper struct {
	aylo   *ayloutil.Scraper
	config collectionConfig
}

func (s *collectionScraper) ID() string { return s.config.SiteID }

func (s *collectionScraper) Patterns() []string {
	slug := strings.ToLower(s.config.StudioName)
	return []string{
		fmt.Sprintf("spicevids.com/collection/%d/%s", s.config.CollectionID, slug),
	}
}

func (s *collectionScraper) MatchesURL(u string) bool {
	m := collectionMatchRe.FindStringSubmatch(u)
	if m == nil {
		return false
	}
	id, _ := strconv.Atoi(m[1])
	return id == s.config.CollectionID
}

func (s *collectionScraper) ListScenes(ctx context.Context, studioURL string, opts scraper.ListOpts) (<-chan scraper.SceneResult, error) {
	out := make(chan scraper.SceneResult)
	go s.aylo.Run(ctx, studioURL, opts, out)
	return out, nil
}

type genericScraper struct {
	aylo   *ayloutil.Scraper
	lookup map[int]*collectionScraper
}

func (s *genericScraper) ID() string { return "spicevids" }

func (s *genericScraper) Patterns() []string {
	return []string{
		"spicevids.com",
		"spicevids.com/model/{id}/{slug}",
		"spicevids.com/collection/{id}/{slug}",
		"spicevids.com/category/{id}/{slug}",
		"spicevids.com/series/{id}/{slug}",
	}
}

var genericMatchRe = regexp.MustCompile(`^https?://(?:www\.)?spicevids\.com`)

func (s *genericScraper) MatchesURL(u string) bool {
	if !genericMatchRe.MatchString(u) {
		return false
	}
	if m := collectionMatchRe.FindStringSubmatch(u); m != nil {
		id, _ := strconv.Atoi(m[1])
		if _, known := s.lookup[id]; known {
			return false
		}
	}
	return true
}

func (s *genericScraper) ListScenes(ctx context.Context, studioURL string, opts scraper.ListOpts) (<-chan scraper.SceneResult, error) {
	out := make(chan scraper.SceneResult)
	go s.aylo.Run(ctx, studioURL, opts, out)
	return out, nil
}
