// Package nastymedia scrapes the live Nasty Media Group sites: a hand-
// built network whose tour pages are generated by WYSIWYG Web Builder
// 18 (`<meta name="generator" content="WYSIWYG Web Builder 18 - …">`).
// Each site's `/HOME.html` carries a fixed set of `<div id="wb_Card{N}">`
// cards linking to per-scene static HTML pages (e.g. `/RELLIE.html`),
// with image, date/header line, and short description in nested
// `Card{N}-card-item{0,1,2,3}` children.
//
// Of the 13 stashdb-listed sites, only 4 still resolve and serve a
// HOME page (verified May 2026):
//
//   - coozhound.com — 21 cards (largest catalogue)
//   - msnympho.com — 12 cards
//   - nastynyamateurs.com — 12 cards
//   - urbanamateurs.net — 12 cards
//
// The remaining 9 stashdb children are DNS-dead, parked, return 404, or
// have been domain-squatted (isuckxxx.com now serves a Chinese movie
// review site). They're not covered.
//
// No pagination: HOME.html is the single listing surface. Each card
// provides everything needed for a `models.Scene` (ID from URL slug,
// title from card item1 or item3, thumbnail, optional date), so detail
// pages aren't fetched.
package nastymedia

import (
	"context"
	"fmt"
	"html"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/Wasylq/FSS/internal/httpx"
	"github.com/Wasylq/FSS/models"
	"github.com/Wasylq/FSS/scraper"
)

const studioName = "Nasty Media Group"

// SiteConfig describes one Nasty Media Group sub-site.
type SiteConfig struct {
	ID       string
	BaseURL  string // e.g. "https://www.coozhound.com" — no trailing slash
	SiteName string // shown in Scene.Series
	Patterns []string
	MatchRe  *regexp.Regexp
}

type Scraper struct {
	cfg    SiteConfig
	client *http.Client
}

func New(cfg SiteConfig) *Scraper {
	return &Scraper{
		cfg:    cfg,
		client: httpx.NewClient(30 * time.Second),
	}
}

func (s *Scraper) ID() string         { return s.cfg.ID }
func (s *Scraper) Patterns() []string { return s.cfg.Patterns }
func (s *Scraper) MatchesURL(u string) bool {
	return s.cfg.MatchRe.MatchString(u)
}

func (s *Scraper) ListScenes(ctx context.Context, studioURL string, opts scraper.ListOpts) (<-chan scraper.SceneResult, error) {
	out := make(chan scraper.SceneResult)
	go s.run(ctx, studioURL, opts, out)
	return out, nil
}

// ---- Parser ----

var (
	// cardStartRe matches just the opening `<div id="wb_Card{N}" … class="card" … >`
	// of one card. The card body runs from one match's start to the
	// next match's start (or end of document) — Go RE2 has no
	// look-ahead so we slice manually instead of capturing the body in
	// the regex.
	cardStartRe = regexp.MustCompile(`<div id="wb_Card(\d+)"[^>]*class="card"[^>]*>`)
	// hrefRe — the scene's detail-page anchor inside the card.
	hrefRe = regexp.MustCompile(`<a\s+href="(https?://[^"]+/([A-Z][A-Z0-9_]*)\.html)"`)
	// imgRe — the card's thumbnail.
	imgRe = regexp.MustCompile(`<img[^>]*\bsrc="([^"]+)"`)
	// itemRe — Card{N}-card-item{0..3} text. Multiple items per card.
	itemRe = regexp.MustCompile(`(?s)<div id="Card\d+-card-item(\d+)"[^>]*>(.*?)</div>`)
	// dateRe — recognises WWB date headers like "UPDATE FEBRUARY 15TH, 2025" or
	// "UPDATE :  MAY 15TH , 2026". The `UPDATE` token is optional so
	// item1 lines that are just the date also parse.
	dateRe = regexp.MustCompile(`(?i)(?:UPDATE\s*:?\s*)?(\w+)\s+(\d{1,2})(?:ST|ND|RD|TH)?\s*,\s*(\d{4})`)
	// stripTagsRe — strip inline HTML formatting (<span>, <br>) from
	// captured item text.
	stripTagsRe = regexp.MustCompile(`<[^>]+>`)
	wsRe        = regexp.MustCompile(`\s+`)
)

type cardScene struct {
	slug    string
	url     string
	thumb   string
	header  string // item1 — usually a date header or short title
	desc    string // item3 — usually the scene description / long title
	rawDate string
	dateOK  bool
	date    time.Time
}

// parseCards extracts every scene card from a Nasty Media HOME.html
// page. Cards reference per-scene detail pages by absolute URL; the
// last path component (the `SLUG.html`) serves as the stable Scene ID.
func parseCards(body []byte, baseURL string) []cardScene {
	page := string(body)
	out := make([]cardScene, 0, 16)
	seen := make(map[string]bool, 16)

	starts := cardStartRe.FindAllStringIndex(page, -1)
	for i, loc := range starts {
		end := len(page)
		if i+1 < len(starts) {
			end = starts[i+1][0]
		}
		block := page[loc[1]:end]

		href := hrefRe.FindStringSubmatch(block)
		if href == nil {
			continue
		}
		slug := href[2]
		if seen[slug] {
			continue
		}
		seen[slug] = true

		sc := cardScene{
			slug: slug,
			url:  href[1],
		}

		if im := imgRe.FindStringSubmatch(block); im != nil {
			sc.thumb = absoluteURL(im[1], baseURL)
		}

		items := itemRe.FindAllStringSubmatch(block, -1)
		for _, it := range items {
			text := cleanText(it[2])
			if text == "" {
				continue
			}
			switch it[1] {
			case "1":
				sc.header = text
			case "3":
				sc.desc = text
			}
		}

		// Try to parse a date out of the header line.
		if sc.header != "" {
			if dm := dateRe.FindStringSubmatch(sc.header); dm != nil {
				if d, ok := parseMonthDay(dm[1], dm[2], dm[3]); ok {
					sc.rawDate = sc.header
					sc.date = d
					sc.dateOK = true
				}
			}
		}

		out = append(out, sc)
	}
	return out
}

// parseMonthDay parses month-name + day-of-month + year.
func parseMonthDay(month, day, year string) (time.Time, bool) {
	// Build a canonical "January 2, 2006" string from the captured
	// month name. Month names are ASCII English so a manual first-byte
	// uppercase is enough — avoids the deprecated strings.Title and
	// the heavyweight golang.org/x/text/cases dependency.
	m := strings.ToLower(strings.TrimSpace(month))
	if m == "" {
		return time.Time{}, false
	}
	m = strings.ToUpper(m[:1]) + m[1:]
	s := m + " " + strings.TrimSpace(day) + ", " + strings.TrimSpace(year)
	for _, layout := range []string{"January 2, 2006", "Jan 2, 2006"} {
		if t, err := time.Parse(layout, s); err == nil {
			return t.UTC(), true
		}
	}
	return time.Time{}, false
}

func absoluteURL(rel, base string) string {
	if rel == "" {
		return ""
	}
	if strings.HasPrefix(rel, "http") {
		return rel
	}
	if strings.HasPrefix(rel, "//") {
		return "https:" + rel
	}
	if strings.HasPrefix(rel, "/") {
		return strings.TrimRight(base, "/") + rel
	}
	return strings.TrimRight(base, "/") + "/" + rel
}

func cleanText(s string) string {
	if s == "" {
		return ""
	}
	s = stripTagsRe.ReplaceAllString(s, " ")
	s = html.UnescapeString(s)
	s = strings.ReplaceAll(s, " ", " ")
	s = wsRe.ReplaceAllString(s, " ")
	return strings.TrimSpace(s)
}

// ---- run loop ----

func (s *Scraper) run(ctx context.Context, studioURL string, opts scraper.ListOpts, out chan<- scraper.SceneResult) {
	defer close(out)
	scraper.Debugf(1, "nastymedia/%s: fetching HOME", s.cfg.ID)

	body, err := s.fetchHome(ctx)
	if err != nil {
		select {
		case out <- scraper.Error(fmt.Errorf("home: %w", err)):
		case <-ctx.Done():
		}
		return
	}

	cards := parseCards(body, s.cfg.BaseURL)
	scraper.Debugf(1, "nastymedia/%s: %d cards", s.cfg.ID, len(cards))
	if len(cards) > 0 {
		select {
		case out <- scraper.Progress(len(cards)):
		case <-ctx.Done():
			return
		}
	}

	now := time.Now().UTC()
	for _, c := range cards {
		if opts.KnownIDs[c.slug] {
			scraper.Debugf(1, "nastymedia/%s: known ID %q, stopping early", s.cfg.ID, c.slug)
			select {
			case out <- scraper.StoppedEarly():
			case <-ctx.Done():
			}
			return
		}
		select {
		case out <- scraper.Scene(s.toScene(c, studioURL, now)):
		case <-ctx.Done():
			return
		}
	}
}

func (s *Scraper) fetchHome(ctx context.Context) ([]byte, error) {
	resp, err := httpx.Do(ctx, s.client, httpx.Request{
		URL:     s.cfg.BaseURL + "/HOME.html",
		Headers: httpx.BrowserHeaders(httpx.UserAgentFirefox),
	})
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	return httpx.ReadBody(resp.Body)
}

func (s *Scraper) toScene(c cardScene, studioURL string, now time.Time) models.Scene {
	title := c.desc
	if title == "" {
		title = c.header
	}
	if title == "" {
		// Fall back to a cleaned-up version of the slug so we always
		// have *something* — "RELLIE_COOZ" → "Rellie Cooz".
		title = humanizeSlug(c.slug)
	}

	scene := models.Scene{
		ID:        c.slug,
		SiteID:    s.cfg.ID,
		StudioURL: studioURL,
		Title:     title,
		URL:       c.url,
		Thumbnail: c.thumb,
		Studio:    studioName,
		Series:    s.cfg.SiteName,
		ScrapedAt: now,
	}
	if c.dateOK {
		scene.Date = c.date
	}
	if c.desc != "" && c.desc != title {
		scene.Description = c.desc
	}
	return scene
}

// humanizeSlug turns "RELLIE_2025" into "Rellie 2025".
func humanizeSlug(slug string) string {
	parts := strings.Split(slug, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
	}
	return strings.Join(parts, " ")
}
