package adultprime

import (
	"github.com/Wasylq/FSS/internal/scrapers/adultprimeutil"
	"github.com/Wasylq/FSS/scraper"
)

var sites = []adultprimeutil.SiteConfig{
	{SiteID: "adultprime-4kcfnm", Slug: "4Kcfnm", StudioName: "4K CFNM"},
	{SiteID: "adultprime-arousins", Slug: "Arousins", StudioName: "Arousins"},
	{SiteID: "adultprime-bamateurs", Slug: "Bamateurs", StudioName: "bAmateurs"},
	{SiteID: "adultprime-bbvideo", Slug: "BBvideo", StudioName: "BBvideo"},
	{SiteID: "adultprime-beautyandthesenior", Slug: "BeautyAndTheSenior", StudioName: "Beauty And The Senior"},
	{SiteID: "adultprime-bifuck", Slug: "Bifuck", StudioName: "BiFuck"},
	{SiteID: "adultprime-bionixxx", Slug: "Bionixxx", StudioName: "Bionixxx"},
	{SiteID: "adultprime-bondagettes", Slug: "Bondagettes", StudioName: "Bondagettes"},
	{SiteID: "adultprime-boundmenwanked", Slug: "Boundmenwanked", StudioName: "Bound Men Wanked"},
	{SiteID: "adultprime-brasilbimbos", Slug: "Brasilbimbos", StudioName: "Brasil Bimbos"},
	{SiteID: "adultprime-breedbus", Slug: "Breedbus", StudioName: "Breed Bus"},
	{SiteID: "adultprime-cherrycandle", Slug: "Cherrycandle", StudioName: "Cherry Candle"},
	{SiteID: "adultprime-clubbangboys", Slug: "ClubBangBoys", StudioName: "Club Bang Boys"},
	{SiteID: "adultprime-clubcastings", Slug: "Clubcastings", StudioName: "Club Castings"},
	{SiteID: "adultprime-clubsweethearts", Slug: "Clubsweethearts", StudioName: "Club SweetHearts"},
	{SiteID: "adultprime-cockin", Slug: "Cockin", StudioName: "Cockin"},
	{SiteID: "adultprime-cuckoldest", Slug: "Cuckoldest", StudioName: "Cuckoldest"},
	{SiteID: "adultprime-damntight", Slug: "Damntight", StudioName: "DamnTight"},
	{SiteID: "adultprime-daringsexhd", Slug: "Daringsexhd", StudioName: "DaringSex HD"},
	{SiteID: "adultprime-desibang", Slug: "Desibang", StudioName: "Desibang"},
	{SiteID: "adultprime-digitaldesire", Slug: "Digitaldesire", StudioName: "Digital Desire"},
	{SiteID: "adultprime-dirtygunther", Slug: "Dirtygunther", StudioName: "Dirty Gunther"},
	{SiteID: "adultprime-dirtyhospital", Slug: "Dirtyhospital", StudioName: "Dirty Hospital"},
	{SiteID: "adultprime-distorded", Slug: "Distorded", StudioName: "Distorded"},
	{SiteID: "adultprime-elegantraw", Slug: "ElegantRaw", StudioName: "Elegant Raw"},
	{SiteID: "adultprime-familyscrew", Slug: "FamilyScrew", StudioName: "Family Screw"},
	{SiteID: "adultprime-freshpov", Slug: "Freshpov", StudioName: "Fresh POV"},
	{SiteID: "adultprime-fuckingskinny", Slug: "Fuckingskinny", StudioName: "Fucking Skinny"},
	{SiteID: "adultprime-genderflux", Slug: "Genderflux", StudioName: "Genderflux"},
	{SiteID: "adultprime-gonzo2000", Slug: "Gonzo2000", StudioName: "Gonzo 2000"},
	{SiteID: "adultprime-goodmorningsex", Slug: "Goodmorningsex", StudioName: "Good Morning Sex"},
	{SiteID: "adultprime-granddadz", Slug: "Granddadz", StudioName: "Granddadz"},
	{SiteID: "adultprime-grandmams", Slug: "GrandMams", StudioName: "Grandmams"},
	{SiteID: "adultprime-grandparentsx", Slug: "GrandparentsX", StudioName: "GrandparentsX"},
	{SiteID: "adultprime-groupbanged", Slug: "GroupBanged", StudioName: "Group Banged"},
	{SiteID: "adultprime-groupsexgames", Slug: "GroupSexGames", StudioName: "Groupsex Games"},
	{SiteID: "adultprime-hardcoreholiday", Slug: "Hardcoreholiday", StudioName: "Hardcore Holiday"},
	{SiteID: "adultprime-hollandschepassie", Slug: "Hollandschepassie", StudioName: "Hollandsche Passie"},
	{SiteID: "adultprime-homegrowneurope", Slug: "Homegrowneurope", StudioName: "HomeGrown Europe"},
	{SiteID: "adultprime-hotts", Slug: "Hotts", StudioName: "Hot TS"},
	{SiteID: "adultprime-industryinvaders", Slug: "Industryinvaders", StudioName: "Industry Invaders"},
	{SiteID: "adultprime-interraced", Slug: "Interraced", StudioName: "Interraced"},
	{SiteID: "adultprime-jimsclassics", Slug: "Jimsclassics", StudioName: "Jims Classics"},
	{SiteID: "adultprime-jimslip", Slug: "JimSlip", StudioName: "Jim Slip"},
	{SiteID: "adultprime-kingbbc", Slug: "Kingbbc", StudioName: "King BBC"},
	{SiteID: "adultprime-ladylyne", Slug: "Ladylyne", StudioName: "Lady Lyne"},
	{SiteID: "adultprime-larasplayground", Slug: "Larasplayground", StudioName: "Lara's Playground"},
	{SiteID: "adultprime-lesbiansummer", Slug: "Lesbiansummer", StudioName: "Lesbian Summer"},
	{SiteID: "adultprime-letsgobi", Slug: "letsgobi", StudioName: "Let's Go Bi"},
	{SiteID: "adultprime-magmafilm", Slug: "Magmafilm", StudioName: "Magma Film"},
	{SiteID: "adultprime-mamscasting", Slug: "Mamscasting", StudioName: "Mams Casting"},
	{SiteID: "adultprime-manalized", Slug: "Manalized", StudioName: "Manalized"},
	{SiteID: "adultprime-manko88", Slug: "Manko88", StudioName: "Manko88"},
	{SiteID: "adultprime-manupfilms", Slug: "Manupfilms", StudioName: "ManUpFilms"},
	{SiteID: "adultprime-massagesins", Slug: "Massagesins", StudioName: "Massage Sins"},
	{SiteID: "adultprime-maturenl", Slug: "MatureNL", StudioName: "Mature NL"},
	{SiteID: "adultprime-maturevan", Slug: "MatureVan", StudioName: "Mature Van"},
	{SiteID: "adultprime-muchasexo", Slug: "muchasexo", StudioName: "Mucha Sexo"},
	{SiteID: "adultprime-mysexykittens", Slug: "Mysexykittens", StudioName: "My Sexy Kittens"},
	{SiteID: "adultprime-nakedhustlers", Slug: "Nakedhustlers", StudioName: "Naked Hustlers"},
	{SiteID: "adultprime-niceandslutty", Slug: "Niceandslutty", StudioName: "Nice and Slutty"},
	{SiteID: "adultprime-nylonflix", Slug: "Nylonflix", StudioName: "NylonFlix"},
	{SiteID: "adultprime-ogjav", Slug: "Ogjav", StudioName: "OG JAV"},
	{SiteID: "adultprime-oldhans", Slug: "Oldhans", StudioName: "Old Hans"},
	{SiteID: "adultprime-oldiex", Slug: "OldieX", StudioName: "OldieX"},
	{SiteID: "adultprime-pawgqueen", Slug: "Pawgqueen", StudioName: "PawgQueen"},
	{SiteID: "adultprime-peepleak", Slug: "peepleak", StudioName: "Peep Leak"},
	{SiteID: "adultprime-peghim", Slug: "Peghim", StudioName: "Peg Him"},
	{SiteID: "adultprime-perfect18", Slug: "Perfect18", StudioName: "Perfect 18"},
	{SiteID: "adultprime-plumperd", Slug: "Plumperd", StudioName: "Plumperd"},
	{SiteID: "adultprime-pornstarclassics", Slug: "Pornstarclassics", StudioName: "Pornstar Classics"},
	{SiteID: "adultprime-pornstarslive", Slug: "Pornstarslive", StudioName: "Pornstars Live"},
	{SiteID: "adultprime-prime3dx", Slug: "Prime3dx", StudioName: "Prime 3DX"},
	{SiteID: "adultprime-primelesbian", Slug: "Primelesbian", StudioName: "Prime Lesbian"},
	{SiteID: "adultprime-primemature", Slug: "Primemature", StudioName: "Prime Mature"},
	{SiteID: "adultprime-raweuro", Slug: "RawEuro", StudioName: "Raw Euro"},
	{SiteID: "adultprime-redlightsextrips", Slug: "RedLightSexTrips", StudioName: "Red Light Sex Trips"},
	{SiteID: "adultprime-salsaxxx", Slug: "Salsaxxx", StudioName: "Salsa XXX"},
	{SiteID: "adultprime-sensualheat", Slug: "Sensualheat", StudioName: "Sensual Heat"},
	{SiteID: "adultprime-shadowslaves", Slug: "Shadowslaves", StudioName: "Shadow Slaves"},
	{SiteID: "adultprime-sindeluxe", Slug: "Sindeluxe", StudioName: "SinDeluxe"},
	{SiteID: "adultprime-sinfulraw", Slug: "Sinfulraw", StudioName: "Sinful RAW"},
	{SiteID: "adultprime-sinfulsoft", Slug: "Sinfulsoft", StudioName: "Sinful SOFT"},
	{SiteID: "adultprime-sinfulxxx", Slug: "SinfulXXX", StudioName: "Sinful XXX"},
	{SiteID: "adultprime-southernsins", Slug: "Southernsins", StudioName: "Southern Sins"},
	{SiteID: "adultprime-submissed", Slug: "Submissed", StudioName: "Submissed"},
	{SiteID: "adultprime-sweetfemdom", Slug: "Sweetfemdom", StudioName: "Sweet Femdom"},
	{SiteID: "adultprime-sweetheartsclassics", Slug: "SweetheartsClassics", StudioName: "Sweethearts Classics"},
	{SiteID: "adultprime-swhores", Slug: "Swhores", StudioName: "Swhores"},
	{SiteID: "adultprime-teenrs", Slug: "Teenrs", StudioName: "Teenrs"},
	{SiteID: "adultprime-thepainfiles", Slug: "Thepainfiles", StudioName: "The Painfiles"},
	{SiteID: "adultprime-trannybizarre", Slug: "Trannybizarre", StudioName: "Tranny Bizarre"},
	{SiteID: "adultprime-transhappy", Slug: "Transhappy", StudioName: "Trans Happy"},
	{SiteID: "adultprime-ukflashers", Slug: "Ukflashers", StudioName: "UK Flashers"},
	{SiteID: "adultprime-vlaamschepassie", Slug: "Vlaamschepassie", StudioName: "Vlaamsche Passie"},
	{SiteID: "adultprime-vrteenrs", Slug: "VRTeenrs", StudioName: "VRTeenrs"},
	{SiteID: "adultprime-youngbusty", Slug: "Youngbusty", StudioName: "Young Busty"},
}

func init() {
	for _, cfg := range sites {
		scraper.Register(adultprimeutil.NewScraper(cfg))
	}
}
